import { onboarding } from './onboarding.js';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names:Record<string,string>={PASS:'通过',FAIL:'失败',INCOMPLETE:'未完成',REVIEW:'待复核',NOT_RUN:'尚未运行',FINISHED:'已结束',RUNNING:'执行中',QUEUED:'排队中',PREPARING:'准备中',FINALIZING:'汇总中',CANCELLED:'已取消',CANCEL_REQUESTED:'取消中',ERROR:'执行异常'};
export function dashboard(d:any):string {
  const base=`/space/${encodeURIComponent(d.project.id)}`;
  const latest=new Map<string,any>();
  for(const c of d.cases){const old=latest.get(c.caseId);if(!old||c.version>old.version)latest.set(c.caseId,c);}
  const drafts=[...latest.values()].filter(c=>c.approvalStatus==='DRAFT').length;
  const openDefects=d.defects.filter((f:any)=>!['VERIFIED','REJECTED'].includes(f.status)).length;
  const active=d.executions.filter((r:any)=>['QUEUED','PREPARING','RUNNING','FINALIZING','CANCEL_REQUESTED'].includes(r.lifecycle)).length;
  const metric=(label:string,value:number,note:string,tone='')=>`<article class="metric" data-tone="${tone}"><span class="metric-label">${label}</span><strong class="metric-value">${value.toString().padStart(2,'0')}</strong><small>${note}</small></article>`;
  const rows=d.executions.slice(0,5).map((r:any)=>`<tr><td><a href="/runs/${encodeURIComponent(r.id)}">${esc(r.buildId??'未声明构建')}</a><small>${esc(String(r.createdAt??'').replace('T',' ').slice(0,16))}</small></td><td><span class="badge ${esc(r.lifecycle)}">${esc(names[r.lifecycle]??r.lifecycle)}</span></td><td><span class="badge ${esc(r.acceptanceStatus)}">${esc(names[r.acceptanceStatus]??r.acceptanceStatus)}</span></td><td><a href="/runs/${encodeURIComponent(r.id)}/report">查看证据 ↗</a></td></tr>`).join('');
  return `<div class="page-heading"><div><span class="eyebrow">PROJECT OVERVIEW</span><h1>${esc(d.project.name)}</h1><p>掌握这次交付的进展、问题，以及还需要确认的事。</p></div><a class="primary-link" href="${base}?tab=missions#create-mission">＋ 创建测试任务</a></div>
  <section class="mission-hero"><div><span class="eyebrow">FROM REQUIREMENTS TO EVIDENCE</span><h2>让测试沿着业务发生。<br>让每个结论，都有证据。</h2><p>把产品资料、测试环境和验收目标连起来，逐步完成测试设计、执行与修复复测。</p><a class="primary-link" href="${base}?tab=missions">准备一次交付验收 →</a></div><div class="hero-graphic" aria-hidden="true"><div class="orbit"><span class="orbit-center">◎</span><span class="orbit-node">需求依据</span><span class="orbit-node bottom">执行证据 ↗</span></div></div></section>
  <div class="metric-grid">${metric('待审阅用例',drafts,'按当前返回的最新用例版本','warning')}${metric('进行中的验收',active,'排队、准备、执行与汇总')}${metric('待处理缺陷',openDefects,'未核验修复或驳回','danger')}${metric('可用测试环境',d.environments.filter((e:any)=>!e.isProduction).length,'已登记的非生产环境')}</div>
  <div class="dashboard-grid">${onboarding(d)}<section class="card"><div class="panel-title"><h2>现在需要关注</h2><span class="badge">下一步</span></div><div class="action-row"><span class="action-number">01</span><div><b>确认业务预期</b><p>${drafts?`${drafts} 个最新用例等待审阅。`:'检查资料冲突与已批准的验收范围。'}</p></div><a href="${base}?tab=missions#case-review">审阅 →</a></div><div class="action-row"><span class="action-number">02</span><div><b>检查执行准备</b><p>核对账号角色、目标构建与测试数据。</p></div><a href="${base}?tab=integrations">配置 →</a></div><div class="action-row"><span class="action-number">03</span><div><b>跟进缺陷与复测</b><p>${openDefects?`${openDefects} 项问题需要处理。`:'新构建沿用原来的标准，保留历史失败。'}</p></div><a href="${base}?tab=assessment">查看 →</a></div><p class="section-note">待办根据现有记录展示；账号是否有效、业务是否满足，需实际执行验证。</p></section></div>
  <section class="card"><div class="panel-title"><h2>最近验收</h2><a href="${base}?tab=execution">全部运行 ↗</a></div>${rows?`<div class="table-wrap"><table><thead><tr><th>目标构建 / 时间</th><th>执行状态</th><th>验收结论</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="empty-state">还没有运行记录。批准测试用例和计划后，开始第一次验收。</div>'}<p class="section-note">统计基于本次工作空间返回的记录。执行结束不代表验收通过；打开证据查看完整范围与未验证项。</p></section>`;
}
