import type {FastifyInstance} from 'fastify';
import {api,ApiError} from './api.js';
import {layout,errorPage} from './pages.js';
const e=(x:unknown)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const u=(x:unknown)=>encodeURIComponent(String(x));
const statuses:Record<string,string>={CANDIDATE:'待确认',CONFIRMED:'已确认',FIX_PENDING:'待修复',READY_FOR_RETEST:'待复测',VERIFIED:'已验证修复',REJECTED:'已排除',REOPENED:'再次出现'};
const style='<style>.triage-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:start}.triage-form label{display:block;margin:14px 0}.triage-form input,.triage-form select,.triage-form textarea{width:100%;max-width:100%;box-sizing:border-box;padding:12px;border:1px solid #cedbd3;border-radius:8px;font:inherit}.triage-form :focus-visible{outline:3px solid #288470;outline-offset:3px}.triage-history article{padding:18px 0;border-bottom:1px solid #e0e9e3}.triage-actions{display:flex;gap:16px;flex-wrap:wrap;margin:16px 0}.triage-description{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:760px){.triage-grid{grid-template-columns:1fr}}</style>';
export function registerDefectPages(app:FastifyInstance){
 app.get('/projects/:id/defects',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,q=req.query as any;
  try{const params=new URLSearchParams();for(const key of ['page','status','severity','assignedTo'])if(q[key])params.set(key,q[key]);const d=(await api<any>(`/api/projects/${u(id)}/defects?${params}`,{sid})).data;
   const pager=(page:number)=>{const p=new URLSearchParams(params);p.set('page',String(page));return '?'+p.toString();};
   return reply.type('text/html').send(layout('缺陷工作台',style+`<header class="page-heading"><div><span class="eyebrow">ISSUE WORKSPACE</span><h1>从发现问题，到验证修复。</h1><p>共 ${d.total} 项 · 严重度有依据，负责人有记录，每次出现都能追溯。</p></div><a href="/projects/${u(id)}/delivery">交付中心 →</a></header><section class="card"><form class="triage-form triage-actions" method="get"><label>状态<select name="status"><option value="">全部状态</option>${Object.entries(statuses).map(([k,n])=>`<option value="${k}" ${q.status===k?'selected':''}>${n}</option>`).join('')}</select></label><label>严重度<select name="severity"><option value="">全部严重度</option>${['P0','P1','P2','P3'].map(k=>`<option ${q.severity===k?'selected':''}>${k}</option>`).join('')}</select></label><label>负责人<select name="assignedTo"><option value="">全部成员</option>${d.members.map((m:any)=>`<option value="${e(m.userId)}" ${q.assignedTo===m.userId?'selected':''}>${e(m.user.displayName)}</option>`).join('')}</select></label><button>筛选</button></form></section><section class="card triage-history">${d.defects.map((f:any)=>`<article><span class="status-badge">${e(f.severity)} · ${e(statuses[f.status]??f.status)}</span><h2><a href="/defects/${u(f.id)}">${e(f.title)}</a></h2><p>${e(d.members.find((m:any)=>m.userId===f.assignedTo)?.user.displayName??'未分配')} · 共出现 ${f._count.occurrences} 次</p><p>${e(f.severityBasis??'严重度待人工确认')}</p></article>`).join('')||'<p class="empty-state">当前筛选条件下没有缺陷。</p>'}<nav class="triage-actions">${d.page>1?`<a href="${e(pager(d.page-1))}">上一页</a>`:''}<span>第 ${d.page} 页</span>${d.page*d.pageSize<d.total?`<a href="${e(pager(d.page+1))}">下一页</a>`:''}</nav></section>`,{projectId:id}));
  }catch(err){return reply.code(err instanceof ApiError?err.status:500).type('text/html').send(errorPage(e((err as Error).message)));}
 });
 const render=async(id:string,sid:string,page=1,draft:any={},message='')=>{
  const f=(await api<any>(`/api/defects/${u(id)}?page=${page}`,{sid})).data;
  return layout('缺陷详情',style+`<header class="page-heading"><div><span class="eyebrow">ISSUE DETAIL</span><h1>${e(f.title)}</h1><p>${e(statuses[f.status]??f.status)} · ${e(f.severity)} · ${f.total} 次出现</p></div><a href="/projects/${u(f.projectId)}/defects">返回缺陷工作台 →</a></header>${message?`<p role="alert" class="error-box">${e(message)}。输入已保留，请核对最新状态后提交。</p>`:''}<div class="triage-grid"><section class="card"><h2>问题与影响</h2><p class="triage-description">${e(f.description??'尚无补充描述')}</p><h3>严重度依据</h3><p>${e(f.severityBasis??'尚待人工评估')}</p><form class="triage-form" method="post" action="/defects/${u(id)}/update"><input type="hidden" name="expectedUpdatedAt" value="${e(f.updatedAt)}"><label>处理状态<select name="status">${['CONFIRMED','FIX_PENDING','READY_FOR_RETEST','REJECTED'].map(k=>`<option value="${k}" ${(draft.status??f.status)===k?'selected':''}>${statuses[k]}</option>`).join('')}</select></label><label>负责人<select name="assignedTo"><option value="">未分配</option>${f.members.map((m:any)=>`<option value="${e(m.userId)}" ${(draft.assignedTo??f.assignedTo)===m.userId?'selected':''}>${e(m.user.displayName)}</option>`).join('')}</select></label><label>严重度<select name="severity">${['P0','P1','P2','P3'].map(k=>`<option ${(draft.severity??f.severity)===k?'selected':''}>${k}</option>`).join('')}</select></label><label>严重度依据<textarea name="severityBasis" required minlength="5" maxlength="2000" rows="3" placeholder="说明受影响的用户、业务范围和后果">${e(draft.severityBasis??f.severityBasis??'')}</textarea></label><label>本次处理说明<textarea name="reason" required maxlength="2000" rows="3">${e(draft.reason??'')}</textarea></label><button>保存处理记录</button></form></section><section class="card triage-history"><h2>每次出现的记录</h2>${f.occurrences.map((o:any)=>`<article><b>${e(o.buildId??'未声明构建版本')}</b><p>${e(new Date(o.createdAt).toLocaleString('zh-CN'))}</p><a href="/runs/${u(o.runId)}/report">查看当次运行报告 →</a><p>${Array.isArray(o.evidenceRefs)?o.evidenceRefs.map((ref:string)=>`<a href="/artifacts/${u(ref)}">执行证据</a>`).join(' · '):''}</p></article>`).join('')||'<p class="empty-state">暂无执行出现记录。</p>'}<nav class="triage-actions">${page>1?`<a href="?page=${page-1}">上一页</a>`:''}<span>第 ${page} 页</span>${page*f.pageSize<f.total?`<a href="?page=${page+1}">下一页</a>`:''}</nav><h2>验证修复</h2><p>仅接受与原失败运行关联、原用例通过且实际构建已核验的复测。</p><form class="triage-form" method="post" action="/defects/${u(id)}/verify"><label>复测运行<select name="runId" required>${f.runs.map((r:any)=>`<option value="${e(r.id)}">${e(r.buildId??'未声明构建')} · ${e(r.acceptanceStatus)} · ${e(new Date(r.createdAt).toLocaleString('zh-CN'))}</option>`).join('')}</select></label><button ${f.runs.length?'':'disabled'}>核验修复结果</button></form></section></div>`,{projectId:f.projectId});
 };
 app.get('/defects/:id',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');try{return reply.type('text/html').send(await render((req.params as any).id,sid,Math.max(1,Number((req.query as any).page)||1)));}catch(err){return reply.code(err instanceof ApiError?err.status:500).type('text/html').send(errorPage(e((err as Error).message)));}});
 for(const action of ['update','verify'])app.post('/defects/:id/'+action,async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,b=req.body as any;try{await api(`/api/defects/${u(id)}/${action}`,{sid,method:'POST',body:action==='update'?{...b,assignedTo:b.assignedTo||null}:b});return reply.redirect('/defects/'+u(id));}catch(err){return reply.code(err instanceof ApiError?err.status:422).type('text/html').send(await render(id,sid,1,b,(err as Error).message));}});
}
