import type {FastifyInstance,FastifyRequest,FastifyReply} from 'fastify';
import {randomUUID} from 'node:crypto';
import {api,ApiError} from './api.js';
import {layout,errorPage} from './pages.js';
const e=(x:unknown)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const u=(x:unknown)=>encodeURIComponent(String(x));
const hidden=(name:string,value:unknown)=>`<input type="hidden" name="${e(name)}" value="${e(value)}">`;
const opts=(rows:any[],label:(r:any)=>string)=>rows.map(r=>`<option value="${e(r.id)}">${e(label(r))}</option>`).join('');
const stepNames:Record<string,string>={'document-parse':'解析资料','rule-extract':'提取规则建议','rule-approval-gate':'批准业务规则','case-generate':'生成测试用例','case-approval-gate':'批准测试用例','page-observe':'观察实际页面','plan-approval-gate':'确认执行计划','login-check':'检查账号准备','browser-execute':'执行浏览器测试','evaluate':'评估结果','code-check':'运行工程检查'};
const checkNames:Record<string,string>={NODE_TEST:'Node 原生测试',NODE_VITEST:'Vitest 测试',NODE_JEST:'Jest 测试',NODE_PLAYWRIGHT:'Playwright 浏览器测试',NODE_LINT:'代码规范检查',NODE_TYPECHECK:'TypeScript 类型检查',NODE_BUILD:'项目构建',PYTHON_TEST:'Python 测试'};
const statuses:Record<string,string>={QUEUED:'排队中',RUNNING:'处理中',SUCCEEDED:'已完成',FAILED:'处理失败',CANCELLED:'已取消',DRAFT:'待审阅',APPROVED:'已批准',REJECTED:'已拒绝',PUBLISHED:'可运行',pending:'待处理',in_progress:'提取中',completed:'已完成',failed:'提取失败',cancelled:'已取消'};
const badge=(x:string)=>`<span class="status-badge">${e(statuses[x]??x)}</span>`;
const style=`<style>.delivery-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.delivery-grid>*{min-width:0}.delivery-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.delivery-nav{display:flex;flex-wrap:wrap;gap:16px;margin:20px 0 28px}.delivery-card{border-top:3px solid #487962}.delivery-card p{color:#657269;line-height:1.75}.delivery-card h2{font-size:22px}.delivery-number{font-size:40px;line-height:1.2;letter-spacing:-2px;font-weight:600;color:#254d3b}.delivery-step{font-size:12px;letter-spacing:2px;color:#718377}.delivery-list article{padding:18px 0;border-bottom:1px solid #e5e9e4}.delivery-path{overflow-wrap:anywhere}.delivery-progress{width:100%;accent-color:#367759;height:12px}.delivery-grid label{display:block;margin:12px 0}.delivery-grid input,.delivery-grid select,.delivery-grid textarea{max-width:100%;width:100%;box-sizing:border-box}.delivery-grid input[type=checkbox]{width:auto}.delivery-grid input:not([type=checkbox]):not([type=hidden]),.delivery-grid select,.delivery-grid textarea{padding:12px 14px;border:1px solid #cad8ce;border-radius:8px;font:inherit;background:#fff;color:inherit}.delivery-grid :is(input,select,textarea,button,a):focus-visible{outline:3px solid #247d6c;outline-offset:3px}.delivery-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px}.delivery-actions form{margin:0}.delivery-muted{color:#6d796f;font-size:13px}.delivery-banner{padding:20px 24px;border:1px solid #dce8df;background:#f0f6f1;border-radius:14px;margin-bottom:24px}@media(max-width:760px){.delivery-grid,.delivery-grid.two{grid-template-columns:1fr}.delivery-number{font-size:32px}.delivery-nav{gap:12px}}</style>`;
function shell(projectId:string,title:string,body:string){return layout(title,style+`<nav class="delivery-nav" aria-label="交付中心"><a href="/projects/${u(projectId)}/delivery">交付概览</a><a href="/projects/${u(projectId)}/snapshot-changes">多文件变更</a><a href="/projects/${u(projectId)}/delivery#documents">长文档处理</a><a href="/projects/${u(projectId)}/templates">测试模板</a><a href="/projects/${u(projectId)}/review">规则审阅</a><a href="/projects/${u(projectId)}/evidence-retention">证据保留</a><a href="/projects/${u(projectId)}/deployments">隔离部署</a><a href="/projects/${u(projectId)}/release">发布评审</a><a href="/projects/${u(projectId)}/defects">缺陷工作台</a><a href="/projects/${u(projectId)}/agent">测试智能体</a><a href="/projects/${u(projectId)}/integrations">GitHub 集成</a></nav>`+body,{projectId});}
function failure(reply:FastifyReply,error:unknown){return reply.code(error instanceof ApiError?error.status:500).type('text/html').send(errorPage(error instanceof Error?e(error.message):'请求失败'));}
const docLabel=(v:any)=>`${v.title} · 第 ${v.version} 版`;
export function registerDeliveryPages(app:FastifyInstance){
 const get=(path:string,sid:string)=>api<any>(path,{sid}).then(r=>r.data);
 app.get('/projects/:id/evidence-retention',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;
  try{const d=await get(`/api/projects/${u(id)}/evidence-retention`,sid);
   return reply.type('text/html').send(shell(id,'证据保留',`<header class="page-heading"><div><span class="eyebrow">EVIDENCE LIFECYCLE</span><h1>证据有期限，结论有记录。</h1><p>按项目决定执行材料的保留时间，策略变更与清理均留有审计。</p></div></header><div class="delivery-grid two"><section class="card"><h2>保留策略</h2><form method="post" action="/projects/${u(id)}/evidence-retention"><label><input type="checkbox" name="enabled" ${d.policy.enabled?'checked':''}> 启用到期清理</label><label>普通执行证据（天）<input type="number" name="normalDays" value="${d.policy.normalDays}" min="1" max="3650" required></label><label>受限原始证据（天）<input type="number" name="restrictedDays" value="${d.policy.restrictedDays}" min="1" max="3650" required></label><button>保存保留策略</button></form></section><section class="card"><h2>清理范围</h2><p>${e(d.scope)}</p><p>开启后，已达到保留期限的历史执行证据也会进入清理范围。运行中的材料不会被清理。</p><p>证据失效后，报告和统计会如实标记材料不足。历史运行判定与发布决定仍然保留。</p><p>${e(d.note)}</p><p class="delivery-muted">只有项目管理员可以修改此策略。</p></section></div>`));
  }catch(error){return failure(reply,error);}
 });
 app.post('/projects/:id/evidence-retention',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,b=req.body as any;
  try{await api(`/api/projects/${u(id)}/evidence-retention`,{sid,method:'PUT',body:{enabled:b.enabled==='on',normalDays:Number(b.normalDays),restrictedDays:Number(b.restrictedDays)}});return reply.redirect(`/projects/${u(id)}/evidence-retention`);}catch(error){return failure(reply,error);}
 });
 app.get('/projects/:id/delivery',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,page=Math.max(1,Number((req.query as any).page)||1);
  try{
   const [w,reviews,templates,goals]=await Promise.all([get(`/api/projects/${u(id)}/workspace`,sid),get(`/api/projects/${u(id)}/changes?page=${page}`,sid),get(`/api/projects/${u(id)}/workflow-templates`,sid),get(`/api/projects/${u(id)}/goal-proposals?page=${page}`,sid)]);
   const versions=reviews.documents.flatMap((d:any)=>d.versions.map((v:any)=>({...v,title:d.title})));
   return reply.type('text/html').send(shell(id,'交付中心',`<header class="page-heading"><div><span class="eyebrow">RELEASE WORKSPACE</span><h1>让每一次交付，都有据可依。</h1><p>从资料变化到实际执行，在同一个工作空间完成验收。</p></div><a class="button" href="/projects/${u(id)}/templates">开始一次验收 →</a></header>
   <div class="delivery-grid"><section class="card delivery-card"><span class="delivery-step">01 / CONTEXT</span><h2>产品上下文</h2><div class="delivery-number">${w.sourceCounts.parsed}<small style="font-size:14px;letter-spacing:0"> 份已解析资料</small></div><p>识别这次交付改变了哪些要求，保留每条规则的原始依据。</p><a href="/projects/${u(id)}/snapshot-changes">比较仓库版本 →</a></section><section class="card delivery-card"><span class="delivery-step">02 / EXECUTION</span><h2>验收流程</h2><div class="delivery-number">${templates.templates.filter((t:any)=>t.status==='PUBLISHED').length}<small style="font-size:14px;letter-spacing:0"> 个可运行模板</small></div><p>发布验收、原标准复测、工程体检，各有明确范围和完成条件。</p><a href="/projects/${u(id)}/templates">选择测试模板 →</a></section><section class="card delivery-card"><span class="delivery-step">03 / EVIDENCE</span><h2>结果与证据</h2><div class="delivery-number">${w.baselines.length}<small style="font-size:14px;letter-spacing:0"> 个验收基线</small></div><p>模型建议先审阅，执行结果可追溯。流程结束后查看实际结论。</p><a href="/workflows/project/${u(id)}">查看运行记录 →</a></section></div>
   <div class="delivery-grid two" style="margin-top:24px"><section class="card"><h2>描述你的验收目标</h2><p class="delivery-muted">系统依据当前资料与可用工具提出建议，审阅后再决定执行范围。</p><form method="post" action="/projects/${u(id)}/delivery/propose">${hidden('idempotencyKey',randomUUID())}<label>这次要验证什么？<textarea name="goal" required maxlength="4000" rows="4" placeholder="例如：检查这次审批金额调整，是否影响旧订单和不同角色的权限。"></textarea></label><label>测试环境<select name="environmentId"><option value="">尚未配置</option>${opts(w.environments,(x:any)=>x.name)}</select></label><fieldset><legend>依据资料</legend>${versions.filter((v:any)=>v.parseStatus==='PARSED').map((v:any)=>`<label><input type="checkbox" name="documentVersionIds" value="${e(v.id)}"> ${e(docLabel(v))}</label>`).join('')||'<p>尚无已解析资料。规划将明确列出资料缺口。</p>'}</fieldset><button>生成验收建议</button></form></section><section class="card delivery-list"><h2>最近的规划</h2>${goals.proposals.map((p:any)=>`<article><b>${e(p.goal)}</b> ${badge(p.status)}<p>${p.suggestedTools.length} 项建议 · ${p.blockers.length} 项条件待补齐</p>${p.blockers.map((b:any)=>`<p class="delivery-muted">${e(b.description)}</p>`).join('')}<a href="/projects/${u(id)}/agent">审阅规划并创建任务 →</a></article>`).join('')||'<p class="empty-state">还没有目标规划。写下本次交付最关心的问题。</p>'}</section></div>
   <section class="card delivery-list" id="documents" style="margin-top:24px"><h2>长文档处理</h2><p>按块跟踪提取进度。部分完成的结果不会被标记为完整提取。</p>${versions.map((v:any)=>`<article><a href="/projects/${u(id)}/documents/${u(v.id)}/chunks">${e(docLabel(v))}</a> <span class="delivery-muted">${e(v.parseStatus==='PARSED'?'可开始分块':'先完成资料解析')}</span></article>`).join('')||`<p class="empty-state">上传第一份产品资料，建立验收依据。</p><a href="/projects/${u(id)}/review">上传资料 →</a>`}</section><nav><p>资料第 ${page} 页</p>${page>1?`<a href="?page=${page-1}">上一页</a>`:""} ${page*30<reviews.selectionTotal?`<a href="?page=${page+1}">下一页</a>`:""}</nav>`));
  }catch(error){return failure(reply,error);}
 });
 app.post('/projects/:id/delivery/propose',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,b=req.body as any;
  try{const docs=b.documentVersionIds?(Array.isArray(b.documentVersionIds)?b.documentVersionIds:[b.documentVersionIds]):[];const result=await api<any>(`/api/projects/${u(id)}/goal-proposals/propose`,{sid,method:'POST',body:{goal:b.goal,idempotencyKey:b.idempotencyKey,documentVersionIds:docs,...(b.environmentId?{environmentId:b.environmentId}:{})}});return reply.redirect(`/jobs/${u(result.data.jobId)}`);}catch(error){return failure(reply,error);}
 });
 app.get('/projects/:id/documents/:versionId/chunks',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id,versionId}=req.params as any;
  try{const d=await get(`/api/projects/${u(id)}/documents/${u(versionId)}/chunks`,sid),base=`/projects/${u(id)}/documents/${u(versionId)}/chunks`;
   const done=d.coverage.processed?.length??0,total=d.manifest?.chunkCount??0;
   const form=(action:string,label:string,extra='')=>`<form method="post" action="${base}/${action}">${hidden('idempotencyKey',randomUUID())}${extra}<button>${label}</button></form>`;
   return reply.type('text/html').send(shell(id,'长文档进度',`<header class="page-heading"><div><span class="eyebrow">DOCUMENT PROCESSING</span><h1>每一段要求，都在处理范围内。</h1><p>${e(d.coverage.note)}</p></div><a href="${base}">刷新状态</a></header><section class="delivery-banner"><div class="delivery-number">${done}<small style="font-size:18px;letter-spacing:0"> / ${total} 块已完成</small></div><progress class="delivery-progress" max="${Math.max(1,total)}" value="${done}" aria-label="文档处理进度"></progress></section>
   ${d.manifest?`<section class="card delivery-grid two"><div><h2>全文处理预算</h2><p>未知或中断的调用仍保留额度，重试不会清零。token 是保守预留量，实际账单以模型服务商为准。</p><form method="post" action="${base}/budget"><label>最多调用次数<input type="number" name="maxModelCalls" min="1" max="10000" value="${d.budget?.limits.maxModelCalls??100}" required></label><label>累计 token 保留上限<input type="number" name="maxReservedTokens" min="1000" max="20000000" value="${d.budget?.limits.maxReservedTokens??2000000}" required></label><label>本次授权持续分钟<input type="number" name="minutes" min="1" max="1440" value="60" required></label><button>保存并授权全文预算</button></form></div><div><h2>继续处理全部未完成块</h2><p>已预留 ${d.budget?.reservedTokens??0} token · 已发起 ${d.budget?.usedCalls??0} 次调用。</p>${d.budget?form('process','处理剩余块'): '<p>先设置预算再开始。</p>'}<p>失败时保留完成块，修复条件后可以再次开始。取消入口位于作业详情。</p></div></section>`:''}
   ${!d.manifest?`<section class="card"><h2>开始分块</h2><p>将资料拆为有来源记录的片段，再逐块提取。生成结果仍需人工审阅。</p>${form('start','创建分块清单')}</section>`:''}
   <section class="card delivery-list">${d.chunks.map((c:any)=>`<article><h3>第 ${c.seq+1} 块 ${badge(c.status)}</h3><p class="delivery-muted">已尝试 ${c.attempts} 次${c.status==='in_progress'?' · 执行状态会持久保存':''}</p>${['pending','failed','cancelled'].includes(c.status)?form('extract','提取这一块',hidden('chunkId',c.chunkId)):''}</article>`).join('')||'<p class="empty-state">创建清单后将在这里显示实际块进度。</p>'}</section>
   ${d.coverage.complete?`<section class="card"><h2>完整结果已就绪</h2><p>检查来源和结果校验和后，合并为待批准规则；不会自动批准业务要求。</p>${form('drafts','生成待审阅规则')}</section>`:''}`));
  }catch(error){return failure(reply,error);}
 });
 app.post('/projects/:id/documents/:versionId/chunks/:action',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id,versionId,action}=req.params as any,b=req.body as any;
  try{
   if(!['start','extract','drafts','process','budget'].includes(action))throw new ApiError(404,'NOT_FOUND','操作不存在');
   const base=`/api/projects/${u(id)}/documents/${u(versionId)}/chunks`;
   const path=action==='start'?base:action==='extract'?`${base}/${u(b.chunkId)}/extract`:`${base}/${action}`;
   const body=action==='budget'?{mode:'real',limits:{maxModelCalls:Number(b.maxModelCalls),maxReservedTokens:Number(b.maxReservedTokens),perCallTokenLimit:100000,maxWallClockMs:Number(b.minutes)*60000}}:action==='process'?{idempotencyKey:b.idempotencyKey}:action==='start'?{idempotencyKey:b.idempotencyKey,mode:'real',strategyParams:{maxCharsPerChunk:6000,contextOverlapChars:300,modelBudgetChars:40000}}:action==='extract'?{idempotencyKey:b.idempotencyKey,mode:'real'}:{};
   const result=await api<any>(path,{sid,method:action==='budget'?'PUT':'POST',body});if(action==='budget')return reply.redirect(`/projects/${u(id)}/documents/${u(versionId)}/chunks`);return reply.redirect(`/jobs/${u(result.data.jobId)}`);
  }catch(error){return failure(reply,error);}
 });
 app.get('/projects/:id/templates',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;
  try{const [d,w]=await Promise.all([get(`/api/projects/${u(id)}/workflow-templates`,sid),get(`/api/projects/${u(id)}/workspace`,sid)]);
   return reply.type('text/html').send(shell(id,'测试模板',`<header class="page-heading"><div><span class="eyebrow">TEST PLAYBOOKS</span><h1>选择一条可靠的验收路径。</h1><p>每次运行固定模板版本，变更和审批均有记录。</p></div><form method="post" action="/projects/${u(id)}/templates/install"><button>安装三种内置模板</button></form><a href="/projects/${u(id)}/templates/editor">组合新模板 →</a></header><div class="delivery-grid">${d.templates.map((t:any)=>`<section class="card delivery-card"><span class="delivery-step">VERSION ${t.version}</span><h2>${e(t.name)}</h2>${badge(t.status)}<p>${t.nodes.length} 个步骤 · 最多 ${t.defaultParallelism} 个节点同时处理</p><ol>${t.nodes.map((n:any)=>`<li>${e(stepNames[n.capabilityKey]??n.key)}${n.isApprovalGate?' · 人工确认':''}</li>`).join('')}</ol>${t.status==='PUBLISHED'?`<form method="post" action="/projects/${u(id)}/templates/run">${hidden('templateId',t.id)}${hidden('idempotencyKey',randomUUID())}${t.nodes.every((n:any)=>n.capabilityKey==='code-check')?`<label>GitHub 仓库<input type="url" name="repositoryUrl" required placeholder="https://github.com/团队/项目"></label><label>提交版本（完整 SHA）<input name="commitSha" pattern="[a-f0-9]{40}" required></label><label>项目子目录<input name="subdirectory" value=""></label><label>检查类型<select name="kind">${['NODE_TEST','NODE_VITEST','NODE_JEST','NODE_PLAYWRIGHT','NODE_LINT','NODE_TYPECHECK','NODE_BUILD','PYTHON_TEST'].map(k=>`<option value="${k}">${checkNames[k]}</option>`).join('')}</select></label>`:`<label>测试环境<select name="environmentId" required>${opts(w.environments,(x:any)=>x.name)}</select></label><label>验收基线<select name="baselineId" required>${opts(w.baselines,(x:any)=>x.name)}</select></label><p class="delivery-muted">从已有批准基线执行。新需求请先进入资料与规则审阅流程。</p>`}<button>运行此模板</button></form>`:'<p>模板发布后才可运行。</p>'}</section>`).join('')||'<section class="card"><h2>还没有模板</h2><p>项目管理员可以安装发布验收、原标准复测和工程体检模板。</p></section>'}</div>`));
  }catch(error){return failure(reply,error);}
 });
 app.post('/projects/:id/templates/install',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;try{await api(`/api/projects/${u(id)}/workflow-templates/builtins`,{sid,method:'POST',body:{}});return reply.redirect(`/projects/${u(id)}/templates`);}catch(error){return failure(reply,error);}});
 app.post('/projects/:id/templates/run',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,b=req.body as any;
  try{const inputs=b.repositoryUrl?{codeCheck:{repositoryUrl:b.repositoryUrl,commitSha:b.commitSha,subdirectory:b.subdirectory??'',kind:b.kind}}:{environmentId:b.environmentId,baselineId:b.baselineId};const r=await api<any>(`/api/projects/${u(id)}/workflows`,{sid,method:'POST',body:{templateId:b.templateId,idempotencyKey:b.idempotencyKey,inputs}});return reply.redirect(`/workflows/${u(r.data.workflowId)}`);}catch(error){return failure(reply,error);}
 });
 app.get('/projects/:id/snapshot-changes',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;
  try{
   const page=Math.max(1,Number((req.query as any).page)||1);
   const [d,w]=await Promise.all([get(`/api/projects/${u(id)}/snapshot-changes?page=${page}`,sid),get(`/api/projects/${u(id)}/workspace`,sid)]);
   const snapshots=w.snapshots.filter((s:any)=>s.inventory);
   const label=(s:any)=>`${new Date(s.createdAt).toLocaleString('zh-CN')} · ${s.commitSha.slice(0,8)} · ${s.subdirectory||'仓库根目录'}`;
   return reply.type('text/html').send(shell(id,'多文件变更',`<header class="page-heading"><div><span class="eyebrow">SOURCE CHANGES</span><h1>看清变化，再更新验收标准。</h1><p>对比固定的仓库版本，逐文件确认影响；旧基线完整保留。</p></div></header><div class="delivery-grid two"><section class="card"><h2>选择两个仓库快照</h2><p class="delivery-muted">旧快照如果没有扫描记录，需要重新接入仓库。解析失败的文件会保留为待核实项。</p><form method="post" action="/projects/${u(id)}/snapshot-changes">${hidden('idempotencyKey',randomUUID())}<label>当前验收基线<select name="baselineId" required>${opts(w.baselines,(x:any)=>x.name)}</select></label><label>旧快照<select name="oldSnapshotId" required>${opts(snapshots,label)}</select></label><label>新快照<select name="newSnapshotId" required>${opts(snapshots,label)}</select></label><button ${snapshots.length<2||!w.baselines.length?'disabled':''}>分析多文件变化</button></form>${snapshots.length<2?`<p>至少需要两个具有扫描记录的快照。</p><a href="/space/${u(id)}?tab=context">接入仓库 →</a>`:''}</section><section class="card delivery-list"><h2>比较记录 <small>${d.total} 次</small></h2>${d.changes.map((r:any)=>`<article><a href="/snapshot-changes/${u(r.id)}">${e(new Date(r.createdAt).toLocaleString('zh-CN'))}</a> ${badge(r.job.status)}<p class="delivery-muted">${r.oldFiles.length} 个旧文件 → ${r.newFiles.length} 个新文件</p>${r.job.error?`<p class="error-box">${e(r.job.error.message)}</p>`:''}</article>`).join('')||'<p class="empty-state">还没有比较记录。选择两个版本开始分析。</p>'}<div class="delivery-actions">${page>1?`<a href="?page=${page-1}">上一页</a>`:''}${page*30<d.total?`<a href="?page=${page+1}">下一页</a>`:''}</div></section></div>`));
  }catch(error){return failure(reply,error);}
 });
 app.post('/projects/:id/snapshot-changes',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;try{const r=await api<any>(`/api/projects/${u(id)}/snapshot-changes`,{sid,method:'POST',body:req.body});return reply.redirect(`/snapshot-changes/${u(r.data.snapshotChangeId)}`);}catch(error){return failure(reply,error);}});
 app.get('/snapshot-changes/:id',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;
  try{
   const r=await get(`/api/snapshot-changes/${u(id)}`,sid),reviews=await get(`/api/projects/${u(r.projectId)}/changes`,sid);
   const kinds:Record<string,string>={added:'新增资料',removed:'已删除',modified:'内容变化',renamed:'重命名',uncertain:'待核实',unchanged:'未变化'};
   const changes=r.output?.fileChanges??[],complete=r.output?.complete===true;
   const decision=(kind:string)=>({modified:'MODIFIED_REVIEWED',added:'ADDED_APPROVED',removed:'REMOVED_WITH_REASON',renamed:'RENAMED_CONFIRMED',uncertain:'UNCERTAIN_MANUAL'}[kind]);
   return reply.type('text/html').send(shell(r.projectId,'变更复核',`<header class="page-heading"><div><span class="eyebrow">CHANGE REVIEW</span><h1>确认这次变化，意味着什么。</h1><p>${badge(r.job.status)} · ${r.pendingCount} 项待确认</p></div><a href="/snapshot-changes/${u(id)}">刷新状态</a></header>${r.notice?`<div class="delivery-banner">${e(r.notice)}</div>`:''}${r.job.error?`<p class="error-box">${e(r.job.error.message)}</p>`:''}${r.output&&!complete&&!r.legacy?'<div class="delivery-banner">扫描或解析比较仍不完整。补齐缺失资料后重新分析，才能建立完整的新基线。</div>':''}
   <section class="card delivery-list">${changes.map((c:any)=>{
    const task=r.tasks.find((t:any)=>t.oldPath===(c.old?.path??null)&&t.newPath===(c.new?.path??null)),resolved=task?r.resolutions[task.key]:null;
    const relevant=reviews.reviews.filter((v:any)=>v.oldDocumentVersionId===c.old?.documentVersionId&&v.newDocumentVersionId===c.new?.documentVersionId);
    return `<article><h2>${e(kinds[c.kind])} <small class="delivery-path">${e(c.old?.path??c.new?.path)}</small></h2>${c.kind==='renamed'?`<p>新路径：${e(c.new?.path)}</p>`:''}${c.reason?`<p>${e(c.reason)}</p>`:''}${c.spanReport?`<details><summary>查看原文差异（${c.spanReport.changes.length} 处）</summary>${c.spanReport.changes.filter((x:any)=>x.kind!=='unchanged').map((x:any)=>`<div class="delivery-grid two"><blockquote>${e(x.old?.quotedText??'旧版无此内容')}</blockquote><blockquote>${e(x.new?.quotedText??'新版无此内容')}</blockquote></div>`).join('')}</details>`:''}${resolved?'<p>已确认 · 决策已保存</p>':task&&!r.legacy?`<form method="post" action="/snapshot-changes/${u(id)}/resolve">${hidden('fileKey',task.key)}${hidden('decision',decision(c.kind))}${c.kind==='modified'?`<label>已完成的单文件复核<select name="changeReviewId" required>${opts(relevant,(v:any)=>new Date(v.createdAt).toLocaleString('zh-CN'))}</select></label><a href="/projects/${u(r.projectId)}/changes">先完成该资料的规则和用例复核 →</a>`:''}${['removed','uncertain'].includes(c.kind)?'<label>确认依据<textarea name="reason" minlength="5" maxlength="2000" required rows="3"></textarea></label>':''}<button>确认这一项</button></form>`:''}</article>`;
   }).join('')||'<p class="empty-state">比较完成后会在这里显示逐文件变化。</p>'}</section>
   ${!r.legacy&&r.output?`<section class="card"><h2>建立新版验收基线</h2><p>全部文件完成复核后，保留旧版并创建新版规则与用例范围。</p><form method="post" action="/snapshot-changes/${u(id)}/baseline"><label>新版名称<input name="name" maxlength="200" required placeholder="例如：审批调整 · 第二版验收"></label><button ${r.pendingCount||!complete?'disabled':''}>创建新版基线</button></form></section>`:''}`));
  }catch(error){return failure(reply,error);}
 });
 for(const action of ['resolve','baseline'])app.post(`/snapshot-changes/:id/${action}`,async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;try{await api(`/api/snapshot-changes/${u(id)}/${action}`,{sid,method:'POST',body:req.body});return reply.redirect(`/snapshot-changes/${u(id)}`);}catch(error){return failure(reply,error);}});

}
