/** Recover non-sensitive form drafts after server errors. No passwords/files/credentials retained. */
export const formUx=`<script>
(()=>{
const key='aiqa:last-form-draft',read=()=>{try{const d=JSON.parse(sessionStorage.getItem(key)||'null');return d&&Date.now()-d.at<600000?d:null}catch{return null}},clear=()=>{try{sessionStorage.removeItem(key)}catch{}};
function restore(){const d=read();if(!d)return;if(document.querySelector('[data-error-page], [role="alert"]')){d.recover=true;try{sessionStorage.setItem(key,JSON.stringify(d))}catch{}const error=document.querySelector('[data-error-page]');if(error&&!error.querySelector('[data-draft-return]')&&d.source.startsWith('/')&&!d.source.startsWith('//')){const a=document.createElement('a');a.dataset.draftReturn='true';a.href=d.source;a.textContent='返回填写页面（保留非敏感输入）';a.className='primary-link';error.append(a)}return}
 if(d.recover&&location.pathname+location.search===d.source){for(const form of document.forms){if(form.action!==d.action)continue;for(const item of d.fields){const fields=[...form.elements].filter(x=>x.name===item.name);for(const field of fields){if(field.type==='checkbox'||field.type==='radio')field.checked=item.values.includes(field.value);else if(field.tagName==='SELECT'&&field.multiple){for(const option of field.options)option.selected=item.values.includes(option.value)}else field.value=item.values[0]||''}}}clear()}else clear()}
restore();window.addEventListener('pageshow',()=>{for(const f of document.forms){delete f.dataset.submitting;f.removeAttribute('aria-busy');for(const b of f.querySelectorAll('[data-submit-pending]')){b.removeAttribute('aria-disabled');b.style.pointerEvents='';delete b.dataset.submitPending}}restore()});
document.addEventListener('submit',event=>{const f=event.target;if(!(f instanceof HTMLFormElement)||f.method.toLowerCase()!=='post'||event.defaultPrevented)return;if(f.dataset.submitting){event.preventDefault();return}f.dataset.submitting='true';f.setAttribute('aria-busy','true');for(const b of f.querySelectorAll('button[type="submit"],button:not([type]),input[type="submit"]')){b.setAttribute('aria-disabled','true');b.dataset.submitPending='true';b.style.pointerEvents='none'}
 if(f.querySelector('input[type=password]')){clear();return}const fields=[];for(const name of new Set([...f.elements].map(x=>x.name).filter(Boolean))){if(/password|secret|token|cookie|credential/i.test(name))continue;const els=[...f.elements].filter(x=>x.name===name&&!['file','password','submit','button'].includes(x.type));const values=els.flatMap(x=>x.type==='checkbox'||x.type==='radio'?(x.checked?[x.value]:[]):x.tagName==='SELECT'&&x.multiple?[...x.selectedOptions].map(o=>o.value):[x.value]);if(els.length)fields.push({name,values})}const data=JSON.stringify({at:Date.now(),source:location.pathname+location.search,action:f.action,fields});try{if(data.length<50000)sessionStorage.setItem(key,data);else clear()}catch{}
});
})();</script>`;
