import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import {api,ApiError} from './api.js';
import {layout,errorPage} from './pages.js';
const e=(x:unknown)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const u=(x:unknown)=>encodeURIComponent(String(x));
const names:Record<string,string>={'document-parse':'解析资料','rule-extract':'提取规则','rule-approval-gate':'批准规则','case-generate':'生成用例','case-approval-gate':'批准用例','page-observe':'观察页面','plan-approval-gate':'批准计划','login-check':'检查账号准备','browser-execute':'浏览器执行','evaluate':'评估结果','code-check':'工程检查'};
const inputLabels:Record<string,string>={documentVersionIds:'资料版本',ruleVersionIds:'规则版本',caseVersionIds:'用例版本',observationId:'页面观察',pinnedPlans:'批准计划',runId:'运行记录'};
const allowed:Record<string,string[]>={'document-parse':['documentVersionIds'],'rule-extract':['documentVersionIds'],'rule-approval-gate':['ruleVersionIds'],'case-generate':['ruleVersionIds'],'case-approval-gate':['caseVersionIds'],'page-observe':['caseVersionIds'],'plan-approval-gate':['caseVersionIds','observationId'],'login-check':['caseVersionIds'],'browser-execute':['caseVersionIds','ruleVersionIds','pinnedPlans'],'evaluate':['runId'],'code-check':[]};
const outputs:Record<string,string[]>={'document-parse':['documentVersionIds'],'rule-extract':['ruleVersionIds'],'rule-approval-gate':['ruleVersionIds'],'case-generate':['caseVersionIds'],'case-approval-gate':['caseVersionIds'],'page-observe':['artifactId'],'plan-approval-gate':['pinnedPlans'],'browser-execute':['runId'],'evaluate':['runId'],'code-check':['verdict']};
export function registerTemplateEditor(app:FastifyInstance){
 const render=async(id:string,sid:string,draft:any={},message='')=>{
  const catalogue=(await api<any>(`/api/projects/${u(id)}/capabilities`,{sid})).data.capabilities.filter((c:any)=>names[c.key]&&c.version===1);
  const initial={name:draft.name??'',key:draft.key??'custom-'+randomUUID().slice(0,8),parallelism:draft.parallelism??1,nodes:Array.isArray(draft.nodes)?draft.nodes:[]};
  const boot=JSON.stringify({initial,catalogue:catalogue.map((c:any)=>({key:c.key,version:c.version,name:names[c.key]})),names,inputLabels,allowed,outputs}).replaceAll('<','\\u003c');
  return layout('组合测试模板',`<style>.editor-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.editor-step{padding:20px;border:1px solid #d6e0da;border-left:4px solid #417664;border-radius:12px;margin:16px 0;background:#fff}.editor-step label{display:block;margin:12px 0}.editor-step input,.editor-step select,.template-form>label input{max-width:100%;width:100%;padding:10px;border:1px solid #c8d6cd;border-radius:6px;box-sizing:border-box}.template-form :focus-visible{outline:3px solid #278575;outline-offset:3px}.editor-step select[multiple]{min-height:90px}@media(max-width:760px){.editor-grid{grid-template-columns:1fr}}</style><header class="page-heading"><div><span class="eyebrow">TEST DESIGN STUDIO</span><h1>把测试步骤，组织成可复用的流程。</h1><p>先保存草稿，检查依赖关系，再发布为固定版本。</p></div><a href="/projects/${u(id)}/templates">返回模板</a></header>${message?`<div role="alert" class="error-box">${e(message)}，表单内容已保留。</div>`:''}<form id="template-editor" class="card template-form" method="post" action="/projects/${u(id)}/templates/editor"><label>模板名称<input name="name" value="${e(initial.name)}" required maxlength="200"></label><input type="hidden" name="key" value="${e(initial.key)}"><label>最多同时处理步骤数<select name="parallelism"><option value="1">1 个</option><option value="2" ${Number(initial.parallelism)===2?'selected':''}>2 个</option></select></label><input type="hidden" name="graph" id="graph"><div id="steps"></div><div class="delivery-actions"><button type="button" id="add-step">添加步骤</button><button type="submit">校验并保存草稿</button></div><p>批准门和账号准备步骤不能跳过；依赖必须先完成。未安装能力时，先返回模板页安装内置模板。</p></form><script>
 const data=${boot};let nodes=data.initial.nodes;const area=document.getElementById('steps');
 function option(value,label,selected){const x=document.createElement('option');x.value=value;x.textContent=label;x.selected=selected;return x;}
 function label(text,control){const x=document.createElement('label');x.append(document.createTextNode(text),control);return x;}
 function select(options,value,onchange,multi=false){const s=document.createElement('select');s.multiple=multi;for(const [v,n]of options)s.append(option(v,n,multi?value.includes(v):value===v));s.addEventListener('change',()=>onchange(multi?Array.from(s.selectedOptions).map(x=>x.value):s.value));return s;}
 function refs(index,field){const result=[];for(let j=0;j<nodes.length;j++){if(j===index)continue;for(const out of data.outputs[nodes[j].capabilityKey]||[])if(!field||out===field||field==='observationId'&&out==='artifactId')result.push(['nodes.'+nodes[j].key+'.'+out,'步骤 '+(j+1)+' · '+(data.inputLabels[out]||out)]);}return result;}
 function draw(){area.replaceChildren();nodes.forEach((n,i)=>{const box=document.createElement('section');box.className='editor-step';const title=document.createElement('h2');title.textContent='步骤 '+(i+1);box.append(title);box.append(label('执行能力',select(data.catalogue.map(c=>[c.key,c.name]),n.capabilityKey,v=>{n.capabilityKey=v;n.isApprovalGate=v.endsWith('-gate');n.inputMapping={};delete n.condition;draw();})));box.append(label('先完成这些步骤（可多选）',select(nodes.flatMap((other,j)=>j===i?[]:[[other.key,'步骤 '+(j+1)+' · '+(data.names[other.capabilityKey]||other.capabilityKey)]]),n.dependsOn||[],v=>{n.dependsOn=v;},true)));const mapping=document.createElement('details'),sum=document.createElement('summary');sum.textContent='指定输入来源（留空使用流程默认值）';mapping.append(sum);for(const field of data.allowed[n.capabilityKey]||[]){mapping.append(label(data.inputLabels[field]||field,select([['','使用默认来源'],...refs(i,field)],n.inputMapping?.[field]||'',v=>{n.inputMapping=n.inputMapping||{};if(v)n.inputMapping[field]=v;else delete n.inputMapping[field];})));}box.append(mapping);
 const budget=document.createElement('input');budget.type='number';budget.min='1';budget.max='1440';budget.value=String(Math.ceil((n.budgetOverride?.maxWallClockMs||600000)/60000));budget.addEventListener('input',()=>{n.budgetOverride={...n.budgetOverride,maxWallClockMs:Number(budget.value)*60000};});box.append(label('步骤最长持续分钟',budget));
 if(!n.isApprovalGate&&n.capabilityKey!=='login-check'){const condition=document.createElement('details'),cs=document.createElement('summary');cs.textContent='可选执行条件';condition.append(cs);condition.append(label('前序输出',select([['','始终执行'],...refs(i)],n.condition?.variable||'',v=>{if(!v){delete n.condition;return;}n.condition={variable:v,operator:'exists',value:true};})));box.append(condition);}
 const remove=document.createElement('button');remove.type='button';remove.textContent='移除此步骤';remove.addEventListener('click',()=>{nodes.splice(i,1);nodes.forEach(x=>x.dependsOn=x.dependsOn.filter(k=>k!==n.key));draw();});box.append(remove);area.append(box);});}
 document.getElementById('add-step').addEventListener('click',()=>{if(nodes.length>=64||!data.catalogue.length)return;const cap=data.catalogue[0].key;nodes.push({key:'step-'+crypto.randomUUID(),capabilityKey:cap,capabilityVersion:1,dependsOn:nodes.length?[nodes.at(-1).key]:[],isApprovalGate:cap.endsWith('-gate'),inputMapping:{}});draw();});document.getElementById('template-editor').addEventListener('submit',event=>{if(!nodes.length){event.preventDefault();return;}document.getElementById('graph').value=JSON.stringify(nodes);});draw();
 </script>`,{projectId:id});
 };
 app.get('/projects/:id/templates/editor',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id;try{return reply.type('text/html').send(await render(id,sid));}catch(err){return reply.code(err instanceof ApiError?err.status:500).type('text/html').send(errorPage(e((err as Error).message)));}});
 app.post('/projects/:id/templates/editor',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const id=(req.params as any).id,b=req.body as any;let nodes:any[]=[];try{nodes=JSON.parse(b.graph);if(!Array.isArray(nodes))throw new Error('步骤格式无效');await api(`/api/projects/${u(id)}/workflow-templates/validate`,{sid,method:'POST',body:{nodes}});const saved=await api<any>(`/api/projects/${u(id)}/workflow-templates`,{sid,method:'POST',body:{key:b.key,name:b.name,nodes,defaultParallelism:Number(b.parallelism)}});return reply.redirect(`/projects/${u(id)}/templates/${u(saved.data.id)}/review`);}catch(err){return reply.code(err instanceof ApiError?err.status:422).type('text/html').send(await render(id,sid,{...b,nodes},(err as Error).message));}});
 app.get('/projects/:id/templates/:templateId/review',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id,templateId}=req.params as any;try{const list=(await api<any>(`/api/projects/${u(id)}/workflow-templates`,{sid})).data.templates,t=list.find((x:any)=>x.id===templateId);if(!t)throw new ApiError(404,'NOT_FOUND','模板不存在');return reply.type('text/html').send(layout('发布模板',`<header class="page-heading"><h1>${e(t.name)}</h1><p>第 ${t.version} 版 · ${t.status==='PUBLISHED'?'已发布':'待发布'}</p></header><section class="card"><ol>${t.nodes.map((n:any)=>`<li><strong>${e(names[n.capabilityKey]??n.capabilityKey)}</strong><p>${n.dependsOn.length?'等待 '+n.dependsOn.map((key:string)=>'步骤 '+(t.nodes.findIndex((x:any)=>x.key===key)+1)).join('、'):'可首先执行'}${n.condition?' · 有执行条件':''}</p></li>`).join('')}</ol>${t.status==='DRAFT'?`<form method="post" action="/projects/${u(id)}/templates/${u(t.id)}/publish"><button>确认并发布固定版本</button></form>`:''}<a href="/projects/${u(id)}/templates">返回模板列表</a></section>`,{projectId:id}));}catch(err){return reply.code(err instanceof ApiError?err.status:500).type('text/html').send(errorPage(e((err as Error).message)));}});
 app.post('/projects/:id/templates/:templateId/publish',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id,templateId}=req.params as any;try{await api(`/api/workflow-templates/${u(templateId)}/publish`,{sid,method:'POST',body:{}});return reply.redirect(`/projects/${u(id)}/templates/${u(templateId)}/review`);}catch(err){return reply.code(err instanceof ApiError?err.status:500).type('text/html').send(errorPage(e((err as Error).message)));}});
}
