import type {FastifyInstance} from 'fastify';
import {api,ApiError} from './api.js';
import {layout} from './pages.js';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function registerBrowserPages(app:FastifyInstance){
 app.get('/space/:id/browser-task',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{await api(`/api/v2/projects/${encodeURIComponent(id)}/browser-presets`,{sid});return reply.type('text/html').send(layout('配置网站自主测试',`
<style>.browser-hero{padding:32px;border-radius:20px;background:linear-gradient(130deg,#102c36,#17575d);color:#effffe;margin-bottom:24px}.browser-form{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:20px}.browser-form label{display:block;margin:12px 0}.browser-form input,.browser-form select,.browser-form textarea{width:100%;padding:11px 12px;box-sizing:border-box;border:1px solid #cddbd9;border-radius:9px;background:#fff;color:#173a3d}.browser-form input[type=checkbox]{width:18px;height:18px;margin-right:10px;vertical-align:middle}.browser-row{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.browser-row .row-remove{grid-column:1/-1;justify-self:end;background:transparent;color:#756466;padding:5px;font-size:12px}.browser-row label{font-size:13px}.browser-row label:has(input[type=checkbox]){grid-column:1/-1}.browser-row label input[type=checkbox]{float:left}.browser-form h2{margin-top:20px}@media(max-width:600px){.browser-row{grid-template-columns:1fr}}.browser-row{padding:15px;margin:10px 0;border:1px solid #d5e0df;border-radius:12px}.browser-row input,.browser-row select{margin-top:6px}@media(max-width:800px){.browser-form{grid-template-columns:1fr}}</style>
<section class="browser-hero"><span>WEBSITE AGENT</span><h1>让测试跟着页面变化</h1><p>你确定业务目标和操作范围，智能体逐轮观察页面、选择动作。最后用独立读取检验业务结果。</p></section>
${(req.query as {error?:string}).error?`<p class="error-box">${esc((req.query as {error:string}).error)}</p>`:''}
<div class="browser-form"><form class="card" method="post" id="browser-form"><h2>1. 目标与角色</h2><label>组合名称<input name="name" required maxlength="200"></label><label>业务目标<input name="goal" required maxlength="4000" placeholder="申请人保存采购单，审核人刷新后能看到相同内容"></label><div id="roles"></div><button type="button" id="add-role">＋ 添加角色</button>
<h2>2. 批准的操作范围</h2><p>填写动作、目标元素的可见名称、批准数据。依赖填操作编号，多项用逗号分隔。模型只能选择这些动作。</p><div id="ops"></div><button type="button" id="add-op">＋ 添加操作</button>
<h2>3. 独立结果读取</h2><label>复核角色<input name="checkRole" required placeholder="reviewer"></label><label>定位方式<select name="locatorKind"><option value="testId">测试标识</option><option value="label">字段标签</option><option value="text">可见文字</option><option value="role">可访问性角色 + 名称</option></select></label><label>元素角色（仅最后一种方式需要）<select name="elementRole"><option value="status">状态提示</option><option value="heading">标题</option><option value="textbox">输入框</option><option value="alert">提醒</option><option value="button">按钮</option><option value="link">链接</option><option value="cell">表格单元格</option><option value="row">表格行</option></select></label><label>读取元素的名称或标识<input name="checkTarget" required placeholder="purchase-status"></label><p>保存后，在运行页绑定已批准的业务标准。这里不会创建或改写期望结果。</p><input type="hidden" name="task"><button type="submit">保存测试组合 →</button><p id="browser-note" role="status"></p>
</form><aside><section class="card"><h2>规划与记忆</h2><label>规划策略<select form="browser-form" name="strategy"><option value="semantic-v1">唯一元素匹配 · 免费</option><option value="model-v1">模型规划 · 需设置调用预算</option></select></label><label>经验使用<select form="browser-form" name="memoryPolicy"><option value="none">不使用历史经验</option><option value="approved-memory-v1">使用有效项目经验</option></select></label><p>经验只提供操作线索，不得覆盖业务标准。遇到歧义、验证码或效果不明会停止。</p></section><section class="card"><h2>首次接入</h2><p>管理员先启用能力。登录账号在准备中心登记，测试任务中只填写角色名，不填写密码。</p><form method="post" action="/space/${esc(id)}/browser-task/enable"><button>启用网站测试能力</button></form><p>写接口按精确方法和路径逐条批准。动态接口应先通过高级配置明确授权。</p></section></aside></div>
<script>
const roles=[],ops=[];function field(parent,label,placeholder){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.placeholder=placeholder;l.append(input);parent.append(l);return input;}
function removeRow(box,rows,row){const button=document.createElement('button');button.type='button';button.className='row-remove';button.textContent='移除此项';button.onclick=()=>{rows.splice(rows.indexOf(row),1);box.remove();};box.append(button);}
function addRole(){const box=document.createElement('div');box.className='browser-row';const id=field(box,'角色标识','author'),url=field(box,'起始网址','https://test.example.com'),writes=field(box,'允许的写接口（每项 METHOD /path，用逗号分隔）','POST /api/orders');url.type='url';id.required=url.required=true;const auth=field(box,'使用准备中心已登记的账号','');auth.type='checkbox';const row={id,url,writes,auth};roles.push(row);removeRow(box,roles,row);document.getElementById('roles').append(box);}
function addOp(){const box=document.createElement('div');box.className='browser-row';const id=field(box,'操作编号','save'),role=field(box,'执行角色','author');const kind=document.createElement('select');kind.setAttribute('aria-label','动作类型');for(const [v,t]of [['fill','填写'],['click','点击'],['select','选择'],['reload','刷新'],['navigate','导航'],['switch_tab','切换标签页'],['wait','短暂等待']]){const o=document.createElement('option');o.value=v;o.textContent=t;kind.append(o);}const kindLabel=document.createElement('label');kindLabel.textContent='动作类型';kindLabel.append(kind);box.append(kindLabel);const target=field(box,'目标可见名称（刷新可填 page）','保存'),value=field(box,'批准输入值（填写、选择、导航时填写）',''),after=field(box,'等待完成的操作编号','name'),visual=field(box,'允许截图辅助定位（仅点击）','');visual.type='checkbox';id.required=role.required=target.required=true;const detail=document.createElement('details');const summary=document.createElement('summary');summary.textContent='原生弹窗处理（可选）';detail.append(summary);const dialogType=field(detail,'弹窗类型：alert / confirm / prompt','留空不授权'),dialogMessage=field(detail,'预期弹窗完整文案','必须精确一致'),dialogAction=field(detail,'处理方式：accept / dismiss','accept'),promptText=field(detail,'输入弹窗的批准值（可选）','');box.append(detail);const row={id,role,kind,target,value,after,visual,dialogType,dialogMessage,dialogAction,promptText};ops.push(row);removeRow(box,ops,row);document.getElementById('ops').append(box);}
document.getElementById('add-role').onclick=addRole;document.getElementById('add-op').onclick=addOp;addRole();addOp();document.getElementById('browser-form').onsubmit=function(event){try{this.elements.task.value=JSON.stringify({goal:this.elements.goal.value,strategy:this.elements.strategy.value,maxRounds:30,roles:roles.map(r=>({id:r.id.value,startUrl:r.url.value,authenticate:r.auth.checked,writes:r.writes.value?r.writes.value.split(',').map(x=>{const [method,pathname]=x.trim().split(/\\s+/);return {method,pathname};}):[]})),operations:ops.map(o=>({id:o.id.value,role:o.role.value,kind:o.kind.value,target:o.target.value,visual:o.visual.checked,...(o.dialogType.value?{dialog:{type:o.dialogType.value,message:o.dialogMessage.value,action:o.dialogAction.value||'accept',...(o.promptText.value?{promptText:o.promptText.value}:{})}}:{}),...(['fill','select','navigate'].includes(o.kind.value)?{value:o.value.value}:{}),after:o.after.value?o.after.value.split(',').map(x=>x.trim()):[]}))});}catch(e){event.preventDefault();document.getElementById('browser-note').textContent=e.message;}};
</script>`,{projectId:id,projectName:'网站自主测试'}));}catch(e){return reply.code(e instanceof ApiError?e.status:500).send(esc((e as Error).message));}
 });
 app.post('/space/:id/browser-task/enable',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{const {manifests}=(await api<{manifests:unknown[]}>(`/api/v2/projects/${encodeURIComponent(id)}/browser-presets`,{sid})).data;for(const manifest of manifests){const result=await api<{installationId:string}>(`/api/v2/projects/${encodeURIComponent(id)}/capabilities/install`,{sid,method:'POST',body:{manifest}});await api(`/api/v2/installations/${encodeURIComponent(result.data.installationId)}/authorize`,{sid,method:'POST',body:{scope:['browser:approved-task']}});}return reply.redirect(`/space/${encodeURIComponent(id)}/browser-task`);}catch(e){return reply.redirect(`/space/${encodeURIComponent(id)}/browser-task?error=${encodeURIComponent((e as Error).message)}`);}
 });
 app.post('/space/:id/browser-task',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string},f=req.body as Record<string,string>;
  try{const saved=(await api<{definitionId:string;profileId:string}>(`/api/v2/projects/${encodeURIComponent(id)}/browser-blueprints`,{sid,method:'POST',body:{name:f.name,task:JSON.parse(f.task!),checks:[{nodeId:'verify',role:f.checkRole,target:f.checkTarget,locatorKind:f.locatorKind,elementRole:f.elementRole}],memoryPolicy:f.memoryPolicy}})).data;return reply.redirect(`/space/${encodeURIComponent(id)}/composer/run?definition=${encodeURIComponent(saved.definitionId)}&profile=${encodeURIComponent(saved.profileId)}`);}catch(e){return reply.redirect(`/space/${encodeURIComponent(id)}/browser-task?error=${encodeURIComponent((e as Error).message)}`);}
 });
}
