import type {FastifyInstance} from 'fastify';
import {api,ApiError} from './api.js';
import {layout} from './pages.js';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const split=(v:string)=>v.split(/[\s,]+/).filter(Boolean);
const style=`<style>.eval-hero{padding:28px;border-radius:18px;background:linear-gradient(120deg,#183334,#326966);color:white;margin-bottom:22px}.eval-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.eval-grid strong{font-size:32px;display:block}.eval-form label{display:block;margin:12px 0}.eval-form input,.eval-form select{box-sizing:border-box;width:100%;padding:10px;border:1px solid #cadbd7;border-radius:8px}.eval-scroll{overflow:auto}.eval-row{padding:18px;border:1px solid #dce7e4;border-radius:12px;margin:12px 0}.eval-form .eval-grid{grid-template-columns:repeat(auto-fit,minmax(200px,1fr))}</style>`;
type Flow={id:string;buildId:string;assertionId:string;expected:string;defectId:string|null};
type Trial={flowId:string;result:string;sessionId:string|null;attempts:number;humanInterventionMinutes:number|null;costMicros:number|null};
type Metric={numerator:number;denominator:number;value:number|null;wilson95:number[]|null};
const labels:Record<string,string>={pass_correct:'健康构建通过',fail_correct:'检出已知缺陷',false_positive:'健康误报',false_negative:'未检出目标缺陷',blocked:'阻塞',unknown:'未运行或证据不足'};
export function registerCampaignPages(app:FastifyInstance){
 app.get('/space/:id/evaluations',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{
   const data=(await api<{campaigns:Array<{id:string;name:string;sampleKind:string;flows:number}>}>(`/api/v2/projects/${encodeURIComponent(id)}/campaigns`,{sid})).data;
   return reply.type('text/html').send(layout('效果评测',`${style}<section class="eval-hero"><span>EVIDENCE BEFORE CLAIMS</span><h1>用真实结果衡量测试能力</h1><p>先冻结样本，再执行测试。首次失败、阻塞和未运行都留在统计里。</p></section>${(req.query as {error?:string}).error?`<p class="error-box">${esc((req.query as {error:string}).error)}</p>`:''}
<section class="card"><h2>评测批次</h2>${data.campaigns.length?data.campaigns.map(c=>`<p><a href="/v2/evaluations/${encodeURIComponent(c.id)}">${esc(c.name)}</a> · ${c.sampleKind==='synthetic'?'合成样本':'已授权真实项目'} · ${c.flows} 个流程</p>`).join(''):'<p>还没有评测批次。创建批次前，请准备授权证据和独立验收真值。</p>'}</section>
<details class="card"><summary>冻结一个新评测批次</summary><form method="post" class="eval-form" id="eval-create"><label>批次名称<input name="name" required maxlength="200"></label><label>样本类型<select name="sampleKind"><option value="synthetic">合成样本</option><option value="authorized_real">已授权真实项目</option></select></label><label>授权证据编号（多项以逗号分隔）<input name="authorizationEvidenceIds" required></label><p>证据必须已存入本项目证据库，内容与校验和均可核验。真实项目标签需要授权材料，不会自动授予发布资格。</p><div id="eval-flows"></div><button type="button" id="eval-add">＋ 添加流程</button><input type="hidden" name="flows"><p>冻结后不能改写样本、预期结果或分母；需要变更时创建新批次。</p><button type="submit">冻结样本集合</button></form></details>
<script>
const rows=[];function add(){const box=document.createElement('section');box.className='eval-row eval-grid';const row={};for(const [key,label,placeholder]of [['id','流程编号','checkout-healthy'],['buildId','构建标识','提交 SHA 或版本'],['oracleHash','冻结标准哈希','64 位哈希'],['profileHash','运行配置哈希','64 位哈希'],['assertionId','真值对应断言编号','status'],['defectId','独立缺陷编号（健康样本留空）',''],['sourceEvidenceIds','真值来源证据编号','多个用逗号分隔'],['manualBaselineMinutes','人工基线耗时（分钟，可留空）','']]){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.placeholder=placeholder;input.required=!['defectId','manualBaselineMinutes'].includes(key);if(key==='manualBaselineMinutes'){input.type='number';input.min='0.01';input.step='any';}l.append(input);box.append(l);row[key]=input;}const label=document.createElement('label');label.textContent='独立预期';const select=document.createElement('select');for(const [value,text]of [['pass','健康构建应通过'],['fail','已知缺陷应失败']]){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}label.append(select);box.append(label);row.expected=select;rows.push(row);document.getElementById('eval-flows').append(box);}
document.getElementById('eval-add').onclick=add;add();document.getElementById('eval-create').onsubmit=function(){this.elements.flows.value=JSON.stringify(rows.map(r=>Object.fromEntries(Object.entries(r).map(([key,input])=>[key,key==='sourceEvidenceIds'?input.value.split(/[\\s,]+/).filter(Boolean):key==='manualBaselineMinutes'?(input.value?Number(input.value):null):key==='defectId'?(input.value||null):input.value]))));};
</script>`,{projectId:id,projectName:'效果评测'}));
  }catch(e){return reply.code(e instanceof ApiError?e.status:500).send(layout('效果评测',`<p class="error-box">${esc((e as Error).message)}</p>`));}
 });
 app.post('/space/:id/evaluations',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string},f=req.body as Record<string,string>;
  try{const result=await api<{campaignId:string}>(`/api/v2/projects/${encodeURIComponent(id)}/campaigns`,{sid,method:'POST',body:{name:f.name,sampleKind:f.sampleKind,authorizationEvidenceIds:split(f.authorizationEvidenceIds!),flows:JSON.parse(f.flows!)}});return reply.redirect(`/v2/evaluations/${encodeURIComponent(result.data.campaignId)}`);}catch(e){return reply.redirect(`/space/${encodeURIComponent(id)}/evaluations?error=${encodeURIComponent((e as Error).message)}`);}
 });
 app.get('/v2/evaluations/:id',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{
   const c=(await api<{projectId:string;name:string;sampleKind:string;truthEvidenceValid:boolean;flows:Flow[];firstAttempts:Trial[];metrics:{completion:Metric;knownDefectRecall:Metric;healthyFalsePositive:Metric;unknownCostTrials:number};releaseBlockers:string[]}>(`/api/v2/campaigns/${encodeURIComponent(id)}`,{sid})).data;
   const cards=([['首次正确完成',c.metrics.completion],['独立已知缺陷召回',c.metrics.knownDefectRecall],['健康样本误报',c.metrics.healthyFalsePositive]] as const).map(([label,m])=>`<article class="card"><span>${label}</span><strong>${m.value===null?'—':(m.value*100).toFixed(1)+'%'}</strong><p>${m.numerator} / ${m.denominator}</p><small>${m.wilson95?'95% 区间 '+m.wilson95.map(v=>(v*100).toFixed(1)+'%').join('–'):'样本不足'}</small></article>`).join('');
   return reply.type('text/html').send(layout(c.name,`${style}<section class="eval-hero"><span>${c.sampleKind==='synthetic'?'SYNTHETIC · 合成样本':'AUTHORIZED · 授权项目'}</span><h1>${esc(c.name)}</h1><p>首次登记决定主结果。补跑保留历史，缺证据记为未知。</p></section>${(req.query as {error?:string}).error?`<p class="error-box">${esc((req.query as {error:string}).error)}</p>`:''}${!c.truthEvidenceValid?'<p class="error-box">真值来源证据失效，本批次不能支撑效果结论。</p>':''}<div class="eval-grid">${cards}</div><section class="card eval-scroll"><h2>冻结流程与首次结果</h2><table><thead><tr><th>流程</th><th>预期</th><th>首次结果</th><th>已记录次数</th><th>下一步</th></tr></thead><tbody>${c.flows.map(f=>{const t=c.firstAttempts.find(t=>t.flowId===f.id)!;return `<tr><td>${esc(f.id)}</td><td>${f.expected==='pass'?'应通过':'应检出缺陷'}</td><td>${esc(labels[t.result]??t.result)}${t.sessionId?` · <a href="/v2/sessions/${encodeURIComponent(t.sessionId)}">运行证据</a>`:''}</td><td>${t.attempts}</td><td><a href="/space/${encodeURIComponent(c.projectId)}/composer/run?campaign=${encodeURIComponent(id)}&flow=${encodeURIComponent(f.id)}">${t.sessionId?'补跑':'开始'}</a></td></tr>`;}).join('')}</tbody></table></section>
<section class="card eval-form"><h2>收录已结束的运行</h2><form method="post" action="/v2/evaluations/${esc(id)}/record"><label>运行编号<input name="sessionId" required></label><label>人工介入分钟数（未记录则留空）<input type="number" name="minutes" min="0" step="any"></label><button>核验证据并收录</button></form><p>只收录运行前已登记的任务。人工时间是操作者声明；当前 ${c.metrics.unknownCostTrials} 次试验费用未计量，不能显示为免费。</p></section><section class="card"><h2>发布判定尚未达成</h2><ul>${c.releaseBlockers.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`,{projectId:c.projectId,projectName:'效果评测'}));
  }catch(e){return reply.code(e instanceof ApiError?e.status:500).send(layout('评测不可用',`<p class="error-box">${esc((e as Error).message)}</p>`));}
 });
 app.post('/v2/evaluations/:id/record',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string},f=req.body as Record<string,string>;
  try{await api(`/api/v2/campaigns/${encodeURIComponent(id)}/record`,{sid,method:'POST',body:{sessionId:f.sessionId,humanInterventionMinutes:f.minutes?Number(f.minutes):null}});return reply.redirect(`/v2/evaluations/${encodeURIComponent(id)}`);}catch(e){return reply.redirect(`/v2/evaluations/${encodeURIComponent(id)}?error=${encodeURIComponent((e as Error).message)}`);}
 });
}
