import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import {api,ApiError} from './api.js';
import {layout} from './pages.js';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const embedded=(v:unknown)=>JSON.stringify(v).replace(/</g,'\\u003c');
export function registerTestPatchPages(app:FastifyInstance){
 app.get('/space/:id/test-patches',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{
   const [list,rules]=await Promise.all([api<{patches:Array<{id:string;status:string;commitSha:string;reviewedAt:string|null}>}>(`/api/v2/projects/${encodeURIComponent(id)}/test-patches`,{sid}),api<{rules:Array<{id:string;statement:string;expectation:string}>}>(`/api/v2/projects/${encodeURIComponent(id)}/test-patches/rules`,{sid})]);
   return reply.type('text/html').send(layout('候选代码测试',`
<style>.patch-form label{display:block;margin:14px 0 6px}.patch-form input,.patch-form select{width:100%;padding:11px;border:1px solid #ccd9d5;border-radius:8px;box-sizing:border-box}.example-card{padding:18px;border:1px solid #d4e3df;border-radius:12px;margin:14px 0}.value-row{display:grid;grid-template-columns:120px 1fr;gap:10px}.patch-list{display:flex;flex-wrap:wrap;gap:12px}</style>
<div class="page-heading"><div><span class="eyebrow">INDEPENDENT TEST ORACLES</span><h1>从业务标准补充代码测试</h1><p>输入来自批准规则的业务样例，生成独立候选补丁。在隔离容器完成健康、缺陷、修复对照后，再评价测试是否有效。</p></div></div>
<div class="patch-list">${list.data.patches.map(p=>`<a class="card" href="/v2/test-patches/${esc(p.id)}">${esc(p.commitSha.slice(0,8))} · ${esc(p.status)} · ${p.reviewedAt?'已审核':'待审核'}</a>`).join('')||'<p>还没有候选测试。</p>'}</div>
<section class="card patch-form"><h2>生成函数测试候选</h2><p class="muted">当前模板支持 Node 和 Python 的具名函数、基础类型参数和返回值。生成过程不调用付费模型；样例期望仍需人工审核。</p><form id="candidate-form">
<label>GitHub 仓库<input name="repositoryUrl" type="url" required placeholder="https://github.com/owner/repository"></label><label>健康基线提交 SHA<input name="commitSha" pattern="[a-f0-9]{40}" required></label>
<label>语言<select name="language"><option value="node">Node.js</option><option value="python">Python</option></select></label><label>模块路径<input name="modulePath" required placeholder="src/approval.mjs"></label><label>函数名称<input name="functionName" required placeholder="needsApproval"></label>
<div id="examples"></div><button type="button" id="add-example">添加业务样例</button><button type="submit">生成待审核补丁 →</button><p id="candidate-note" role="status"></p></form></section>
<script>
const rules=${embedded(rules.data.rules)},project=${embedded(id)},form=document.getElementById('candidate-form'),rows=[];
function valueField(label){const host=document.createElement('label');host.textContent=label;const box=document.createElement('div');box.className='value-row';const type=document.createElement('select');for(const [v,t]of [['number','数字'],['string','文本'],['boolean','布尔'],['null','空值']]){const o=document.createElement('option');o.value=v;o.textContent=t;type.append(o);}const input=document.createElement('input');input.required=true;input.setAttribute('aria-label',label);type.onchange=()=>{input.required=type.value!=='null';input.disabled=type.value==='null';input.placeholder=type.value==='boolean'?'true 或 false':'';};box.append(type,input);host.append(box);return {host,read:()=>{if(type.value==='null')return null;if(type.value==='number'){if(!input.value.trim()||!Number.isFinite(Number(input.value)))throw Error('数字格式不正确');return Number(input.value);}if(type.value==='boolean'){if(!['true','false'].includes(input.value))throw Error('布尔值填写 true 或 false');return input.value==='true';}return input.value;}};}
function add(){if(rows.length>=100)return;const i=rows.length+1,card=document.createElement('div');card.className='example-card';const title=document.createElement('h3');title.textContent='业务样例 '+i;const rule=document.createElement('select');rule.required=true;rule.setAttribute('aria-label','样例 '+i+' 来源规则');for(const r of rules){const option=document.createElement('option');option.value=r.id;option.textContent=r.statement+' → '+r.expectation;rule.append(option);}const argsHost=document.createElement('div'),args=[];function addArg(){const f=valueField('样例 '+i+' 参数 '+(args.length+1));args.push(f);argsHost.append(f.host);}addArg();const more=document.createElement('button');more.type='button';more.textContent='增加参数';more.onclick=()=>{if(args.length<20)addArg();};const expected=valueField('样例 '+i+' 预期结果');card.append(title,rule,argsHost,more,expected.host);document.getElementById('examples').append(card);rows.push({id:'case-'+i,rule,args,expected});}
document.getElementById('add-example').onclick=add;add();form.onsubmit=async event=>{event.preventDefault();const note=document.getElementById('candidate-note'),button=form.querySelector('button[type=submit]');button.disabled=true;try{const body={};for(const key of ['repositoryUrl','commitSha','language','modulePath','functionName'])body[key]=form.elements[key].value;body.examples=rows.map(r=>({id:r.id,ruleVersionId:r.rule.value,args:r.args.map(a=>a.read()),expected:r.expected.read()}));const response=await fetch('/space/'+encodeURIComponent(project)+'/test-patches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.message);location.href='/v2/test-patches/'+encodeURIComponent(result.id);}catch(e){note.textContent=e.message;button.disabled=false;}};
</script>`,{projectId:id,projectName:'代码测试'}));
  }catch(e){return reply.code(e instanceof ApiError?e.status:500).send(esc((e as Error).message));}
 });
 app.post('/space/:id/test-patches',async(req,reply)=>{const sid=req.cookies.web_sid;if(!sid)return reply.code(401).send({message:'请登录'});try{const r=await api(`/api/v2/projects/${encodeURIComponent((req.params as {id:string}).id)}/test-patches`,{sid,method:'POST',body:req.body});return reply.code(r.status).send(r.data);}catch(e){return reply.code(e instanceof ApiError?e.status:500).send({message:(e as Error).message});}});
 app.get('/v2/test-patches/:id',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{
   const d=(await api<{patch:{projectId:string;status:string;reviewedAt:string|null;commitSha:string;validity:unknown};candidate:{input:unknown;output:{files:Array<{path:string;content:string}>;limitations:string[]}};checks:Array<{id:string;status:string;verdict:string|null}>}>(`/api/v2/test-patches/${encodeURIComponent(id)}`,{sid})).data;
   return reply.type('text/html').send(layout('审核候选测试',`<div class="page-heading"><div><span class="eyebrow">TEST PATCH REVIEW</span><h1>审核样例，验证断言强度</h1><p>当前状态：${esc(d.patch.status)} · ${d.patch.reviewedAt?'样例已审核':'等待审核'}。所有代码只新增到测试目录，不覆盖产品实现。</p></div></div>
${(req.query as {error?:string}).error?`<p class="error-box">${esc((req.query as {error:string}).error)}</p>`:''}
<section class="card"><h2>来源和输入样例</h2><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(JSON.stringify(d.candidate.input,null,2))}</pre></section>
${d.candidate.output.files.map(f=>`<section class="card"><h2>${esc(f.path)}</h2><pre style="overflow:auto">${esc(f.content)}</pre></section>`).join('')}
<section class="card"><h2>审核与下载</h2><p>${d.candidate.output.limitations.map(esc).join('；')}</p><form method="post" action="/v2/test-patches/${esc(id)}/approve"><button>确认样例符合独立业务标准，允许隔离执行</button></form><p><a href="/v2/test-patches/${esc(id)}/download">下载 Git 补丁</a></p><form method="post" action="/v2/test-patches/${esc(id)}/reject"><input name="reason" required placeholder="驳回原因"><button class="danger">驳回候选</button></form></section>
<section class="card"><h2>运行对照</h2><p>使用同一份测试补丁，分别执行健康基线、已知缺陷和修复提交。运行器必须已连接本项目。</p><form method="post" action="/v2/test-patches/${esc(id)}/run"><label>对照类型<select name="variant"><option value="healthy">健康基线</option><option value="defect">已知缺陷</option><option value="fix">修复提交</option></select></label><label>提交 SHA<input name="commitSha" required pattern="[a-f0-9]{40}" value="${esc(d.patch.commitSha)}"></label><label><input type="checkbox" name="installDependencies">在隔离网络安装锁定依赖</label><input type="hidden" name="idempotencyKey" value="${randomUUID()}"><button>提交隔离运行</button></form><ul>${d.checks.map(c=>`<li>${esc(c.id)} · ${esc(c.status)} · ${esc(c.verdict??'尚无结果')}</li>`).join('')||'<li>尚未执行。</li>'}</ul><form method="post" action="/v2/test-patches/${esc(id)}/evaluate"><button>核验首轮对照结果</button></form><pre>${esc(JSON.stringify(d.patch.validity,null,2))}</pre></section>`,{projectId:d.patch.projectId,projectName:'代码测试'}));
  }catch(e){return reply.code(e instanceof ApiError?e.status:500).send(esc((e as Error).message));}
 });
 app.get('/v2/test-patches/:id/download',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id}=req.params as {id:string};
  try{const r=await api<{raw:string}>(`/api/v2/test-patches/${encodeURIComponent(id)}/download`,{sid});return reply.type('text/x-diff').header('content-disposition',`attachment; filename="aiqa-${id.replace(/[^a-zA-Z0-9-]/g,'')}.patch"`).send(r.data.raw);}catch(e){return reply.code(e instanceof ApiError?e.status:500).send(esc((e as Error).message));}
 });
 app.post('/v2/test-patches/:id/:action',async(req,reply)=>{
  const sid=req.cookies.web_sid;if(!sid)return reply.redirect('/login');const {id,action}=req.params as {id:string;action:string};if(!['approve','reject','run','evaluate'].includes(action))return reply.code(404).send('未知操作');
  const f=req.body as Record<string,string>;const body=action==='run'?{variant:f.variant,commitSha:f.commitSha,installDependencies:f.installDependencies==='on',timeoutSeconds:120,idempotencyKey:f.idempotencyKey}:action==='reject'?{reason:f.reason}:{};
  try{await api(`/api/v2/test-patches/${encodeURIComponent(id)}/${action}`,{sid,method:'POST',body});return reply.redirect(`/v2/test-patches/${encodeURIComponent(id)}`);}catch(e){return reply.redirect(`/v2/test-patches/${encodeURIComponent(id)}?error=${encodeURIComponent((e as Error).message)}`);}
 });
}
