# generated by datamodel-codegen:
#   filename:  schema.v1.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    constr,
)


class File(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    format: str
    excerpt: str = Field(..., max_length=2000)


class SourceClassificationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[File] = Field(..., max_length=50)
    promptVersion: Literal['sources-v1']


class File1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    category: Literal[
        'BUSINESS_CANDIDATE',
        'API_CONTRACT',
        'RUNTIME_CLUE',
        'TEST_CLUE',
        'UNCLASSIFIED',
    ]
    reason: str = Field(..., max_length=500, min_length=1)


class SourceClassificationOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[File1] = Field(..., max_length=50)


class SourceClassificationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: SourceClassificationInput


class Role(RootModel[str]):
    root: str = Field(..., min_length=1)


class DataSpec1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['create']
    note: str = Field(..., min_length=1)


class Cleanup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['namespace', 'fixture', 'manual']
    note: str | None = None


class Locator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['testId']
    value: str = Field(..., min_length=1)


class Locator1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['role']
    role: str = Field(..., min_length=1)
    name: str | None = None


class Locator2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['label']
    value: str = Field(..., min_length=1)


class Locator3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    value: str = Field(..., min_length=1)


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str
    url: AnyUrl
    title: str
    text: str = Field(..., max_length=20000)


class OnlyIf(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    varName: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')
    operator: Literal['eq', 'neq', 'gt', 'gte', 'lt', 'lte']
    value: str | float | bool


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['literal']
    value: str


class Value2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['captured']
    varName: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assertionId: str
    targetRef: str


class Locator4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-line']
    startLine: int
    endLine: int


class PathItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class Locator5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-heading']
    path: list[PathItem] = Field(..., min_length=1)


class Locator6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-paragraph']
    paragraphIndex: int


class Locator7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-cell']
    tableIndex: int
    row: int
    col: int


class Locator8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pdf-page']
    page: int = Field(..., ge=1)


class Locator9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['image-region']
    bbox: list[float] = Field(..., max_length=4, min_length=4)


class CoverageSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalBlocks: int
    goodSpans: int
    lowSpans: int
    unparsedSpans: int


class ProjectGlossaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term: str
    definition: str


class BusinessField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., min_length=1)
    operator: (
        Literal['gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'in', 'between', 'contains']
        | None
    ) = None
    value: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class Clarification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleDraftKeys: list[str] = Field(..., min_length=1)
    question: str = Field(..., min_length=1)
    kind: Literal['MISSING_INFO', 'CONFLICT', 'AMBIGUITY']


class Step1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str = Field(..., min_length=1)
    action: str = Field(..., min_length=1)
    expectedResult: str | None = None


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputTokens: int
    outputTokens: int
    estimatedCost: float | None = None


class ModelResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parsedJson: Any | None = None
    rawText: str
    repairsApplied: (
        list[Literal['code-fence', 'trailing-comma', 'truncated-json', 'bom']] | None
    ) = []
    provider: Literal['moonshot', 'mock']
    model: str
    requestId: str | None
    usage: Usage
    latencyMs: int
    outcome: Literal['SUCCESS', 'INVALID_OUTPUT', 'TIMEOUT', 'PROVIDER_ERROR']


class TextModelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal[
        'RULE_EXTRACTION',
        'CASE_GENERATION',
        'VISION_DESCRIBE',
        'PLAN_PROPOSAL',
        'SOURCE_CLASSIFICATION',
        'GOAL_PROPOSAL',
    ]
    system: str
    user: str
    outputSchema: Any | None = None
    temperature: float | None = Field(None, ge=0.0, le=1.0)
    maxOutputTokens: int | None = None
    timeoutMs: int = Field(..., ge=1000, le=600000)


class VisionModelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal['VISION_DESCRIBE']
    imageStorageKey: str = Field(..., min_length=1)
    hint: str = Field(..., min_length=1)
    outputSchema: Any | None = None
    timeoutMs: int = Field(..., ge=1000, le=600000)


class UnresolvedItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class StrategyParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxCharsPerChunk: int = Field(..., ge=500, le=50000)
    contextOverlapChars: int = Field(..., ge=0, le=5000)
    modelBudgetChars: int = Field(..., ge=1000, le=200000)


class Expected(RootModel[str]):
    root: str = Field(..., pattern='^-?\\d+(\\.\\d+)?$')


class Expected1(RootModel[str]):
    root: str = Field(..., max_length=2000, min_length=1)


class Precondition(RootModel[str]):
    root: str = Field(None, max_length=1000)


class Unit(RootModel[str]):
    root: str = Field(None, max_length=64, min_length=1)


class AllowedRole(RootModel[str]):
    root: str = Field(..., max_length=80, min_length=1)


class RequiredItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class SecretRef(RootModel[str]):
    root: str = Field(..., max_length=128, min_length=1)


class Permissions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    network: Literal['environment-allowlist', 'declared-origins-only']
    declaredOrigins: list[AnyUrl] | None = Field([], max_length=20)
    secrets: Literal['none', 'declared-refs-only']
    secretRefs: list[SecretRef] | None = Field([], max_length=20, validate_default=True)


class ScopeItem(RootModel[str]):
    root: str = Field(..., max_length=200, min_length=1)


class ModelRoutes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    generator: str = Field(..., max_length=200, min_length=1)
    vision: str = Field(..., max_length=200, min_length=1)
    decision: str = Field(..., max_length=200, min_length=1)


class DependsOnItem(RootModel[str]):
    root: str = Field(..., max_length=200, min_length=1)


class Bindings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['node']
    nodeId: str = Field(..., max_length=200, min_length=1)
    path: str = Field(
        ..., max_length=500, min_length=1, pattern='^[a-zA-Z0-9_.\\[\\]-]+$'
    )
    type: Literal['string', 'number', 'boolean', 'json']


class RetryableErrorClass(RootModel[str]):
    root: str = Field(..., max_length=100, min_length=1)


class Retry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxAttempts: int = Field(..., ge=1, le=10)
    retryableErrorClasses: list[RetryableErrorClass] = Field(..., max_length=20)
    totalDeadlineMs: int = Field(..., ge=1000, le=600000)


class TerminationReason(RootModel[str]):
    root: str = Field(None, max_length=2000)


class MaxCostMicros(RootModel[int]):
    root: int = Field(..., ge=1)


class V2SessionBudget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxWallClockMs: int = Field(..., ge=60000, le=86400000)
    maxActiveMs: int = Field(..., ge=60000, le=86400000)
    maxModelCalls: int = Field(..., ge=1, le=10000)
    maxTokens: int = Field(..., ge=1000, le=100000000)
    maxToolCalls: int = Field(..., ge=1, le=100000)
    maxResources: int = Field(..., ge=1, le=10000)
    maxCostMicros: MaxCostMicros | None


class CostKnownMicros(RootModel[int]):
    root: int = Field(..., ge=0)


class V2SessionUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wallClockMsUsed: int = Field(..., ge=0)
    activeMsUsed: int = Field(..., ge=0)
    modelCallsUsed: int = Field(..., ge=0)
    modelCallsReserved: int = Field(..., ge=0)
    tokensUsed: int = Field(..., ge=0)
    tokensReserved: int = Field(..., ge=0)
    toolCallsUsed: int = Field(..., ge=0)
    toolCallsReserved: int = Field(..., ge=0)
    resourcesCreated: int = Field(..., ge=0)
    costKnownMicros: CostKnownMicros | None


class ResourceKey(RootModel[str]):
    root: str = Field(..., max_length=300, min_length=1)


class ExternalRef(RootModel[str]):
    root: str = Field(..., max_length=500, min_length=1)


class OutputHash(RootModel[str]):
    root: str = Field(None, pattern='^[a-f0-9]{64}$')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str = Field(..., max_length=100)
    message: str = Field(..., max_length=2000)


class Score(RootModel[float]):
    root: float = Field(None, ge=0.0, le=1.0)


class OmittedRef(RootModel[str]):
    root: str = Field(..., max_length=500)


class Budget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokensMax: int = Field(..., ge=100)
    tokensUsed: int = Field(..., ge=0)
    truncated: bool
    omittedRefs: list[OmittedRef] | None = Field(
        [], max_length=5000, validate_default=True
    )


class SupportingEvidenceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal[
        'network', 'console', 'auth_log', 'code_diff', 'observation', 'tool_output'
    ]
    ref: str = Field(..., max_length=500, min_length=1)


class ContradictingEvidenceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal[
        'network', 'console', 'auth_log', 'code_diff', 'observation', 'tool_output'
    ]
    ref: str = Field(..., max_length=500, min_length=1)


class Hypothes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str = Field(..., max_length=2000, min_length=1)
    supportingEvidence: list[SupportingEvidenceItem] | None = Field(
        [], max_length=50, validate_default=True
    )
    contradictingEvidence: list[ContradictingEvidenceItem] | None = Field(
        [], max_length=50, validate_default=True
    )
    status: Literal['open', 'supported', 'refuted', 'unknown'] | None = 'open'


class Target1(RootModel[str]):
    root: str = Field(None, max_length=500)


class Step2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: str = Field(..., max_length=500, min_length=1)
    target: Target1 | None = None


class Severity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    level: Literal['blocker', 'critical', 'major', 'minor', 'trivial']
    basis: str = Field(..., max_length=2000, min_length=1)


class Role3(RootModel[str]):
    root: str = Field(None, max_length=80)


class Ref(RootModel[str]):
    root: str = Field(..., max_length=500, min_length=1)


class Origin1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['approved_rule', 'api_contract', 'approved_property']
    refs: list[Ref] = Field(..., max_length=100, min_length=1)


class File2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., max_length=500, min_length=1)
    contentHash: str = Field(..., pattern='^[a-f0-9]{64}$')


class TotalTests(RootModel[int]):
    root: int = Field(None, ge=0)


class FailedTests(RootModel[int]):
    root: int = Field(None, ge=0)


class KnownDefectsDetected(RootModel[int]):
    root: int = Field(None, ge=0)


class MutantsKilled(RootModel[int]):
    root: int = Field(None, ge=0)


class MutantsTotal(RootModel[int]):
    root: int = Field(None, ge=0)


class WeakPatternsFoundItem(RootModel[str]):
    root: str = Field(..., max_length=500)


class Validity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    knownDefectsDetected: KnownDefectsDetected | None = None
    mutantsKilled: MutantsKilled | None = None
    mutantsTotal: MutantsTotal | None = None
    weakPatternsFound: list[WeakPatternsFoundItem] | None = Field(
        [], max_length=50, validate_default=True
    )


class HumanInterventionMinutes(RootModel[float]):
    root: float = Field(None, ge=0.0)


class CostMicros(RootModel[int]):
    root: int = Field(None, ge=0)


class V2RemoteCapabilityResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['SUCCEEDED', 'FAILED', 'CANCELLED', 'UNKNOWN']
    output: Any = None
    resourceKeys: list[ResourceKey] | None = Field(
        [], max_length=100, validate_default=True
    )
    retryable: bool | None = False
    error: Error | None = None


class Score1(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)


class ExcludedPath(RootModel[str]):
    root: str = Field(..., max_length=1024, min_length=1)


class OldPath(RootModel[str]):
    root: str = Field(..., max_length=1024, min_length=1)


class NewPath(RootModel[str]):
    root: str = Field(..., max_length=1024, min_length=1)


class Totals(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldFiles: int = Field(..., ge=0)
    newFiles: int = Field(..., ge=0)
    unchanged: int = Field(..., ge=0)
    modified: int = Field(..., ge=0)
    added: int = Field(..., ge=0)
    removed: int = Field(..., ge=0)
    renamed: int = Field(..., ge=0)
    uncertain: int = Field(..., ge=0)


class Capability1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., max_length=200, min_length=1)
    name: str = Field(..., max_length=200, min_length=1)
    description: str | None = Field(None, max_length=2000)
    effects: list[Literal['READ', 'WRITE', 'CREATE', 'DELETE']] = Field(
        ..., min_length=1
    )
    requiresEnvironment: bool | None = False
    budgetCategory: Literal['none', 'model', 'browser', 'compute'] | None = 'none'


class GoalProposalAgentInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal: str = Field(..., max_length=4000, min_length=1)
    capabilities: list[Capability1] = Field(..., max_length=200)
    hasDocuments: bool
    environmentConfigured: bool
    promptVersion: Literal['goal-v1']


class SuggestedTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilityKey: str = Field(..., max_length=200, min_length=1)
    reason: str = Field(..., max_length=1000, min_length=1)


class SuggestedBudget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxWallClockMs: int | None = Field(None, ge=60000, le=86400000)
    maxModelCalls: int | None = Field(None, ge=1, le=1000)
    maxToolCalls: int | None = Field(None, ge=1, le=5000)


class Blocker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal[
        'MISSING_DATA',
        'MISSING_ACCOUNT',
        'MISSING_ENV',
        'MISSING_SCOPE',
        'INSUFFICIENT_INFO',
    ]
    description: str = Field(..., max_length=2000, min_length=1)


class GoalProposalAgentOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    suggestedTools: list[SuggestedTool] = Field(..., max_length=20)
    suggestedBudget: SuggestedBudget | None = Field({}, validate_default=True)
    blockers: list[Blocker] | None = Field([], max_length=10, validate_default=True)
    rationale: str = Field(..., max_length=4000, min_length=1)


class Checksum(RootModel[str]):
    root: str = Field(..., pattern='^[a-f0-9]{64}$')


class SizeBytes(RootModel[int]):
    root: int = Field(..., ge=0, le=9007199254740991)


class EnumerationReason(RootModel[str]):
    root: str = Field(..., max_length=1000, min_length=1)


class Reason(RootModel[str]):
    root: str = Field(..., max_length=1000, min_length=1)


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldFiles: int = Field(..., ge=0, le=200)
    newFiles: int = Field(..., ge=0, le=200)
    oldCovered: int = Field(..., ge=0, le=200)
    newCovered: int = Field(..., ge=0, le=200)


class Locator10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-line']
    startLine: int
    endLine: int


class Locator11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-heading']
    path: list[PathItem] = Field(..., min_length=1)


class Locator12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-paragraph']
    paragraphIndex: int


class Locator13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-cell']
    tableIndex: int
    row: int
    col: int


class Locator14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pdf-page']
    page: int = Field(..., ge=1)


class Locator15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['image-region']
    bbox: list[float] = Field(..., max_length=4, min_length=4)


class Role4(RootModel[str]):
    root: str = Field(..., min_length=1)


class Value4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['literal']
    value: str


class Value6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['captured']
    varName: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')


class Items(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., min_length=1)
    operator: (
        Literal['gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'in', 'between', 'contains']
        | None
    ) = None
    value: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class PathModel(RootModel[str]):
    root: str = Field(..., max_length=1024, min_length=1)


class RequestId(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class InputSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['object', 'string', 'number', 'integer', 'boolean', 'array']
    properties: dict[str, InputSchema] | None = None
    required: list[RequiredItem] | None = Field(None, max_length=100)
    additionalProperties: Literal[False] | None = None
    items: InputSchema | None = None
    minLength: int | None = Field(None, ge=0, le=1000000)
    maxLength: int | None = Field(None, ge=1, le=10000000)
    minimum: float | None = None
    maximum: float | None = None
    enum: list[str | float | bool] | None = Field(None, max_length=1000)
    pattern: str | None = Field(None, max_length=500)
    nullable: bool | None = None


class Field0(RootModel[str]):
    root: str = Field(..., pattern='^-?\\d+(\\.\\d+)?$')


class AdditionalProperties1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['node']
    nodeId: str = Field(..., max_length=200, min_length=1)
    path: str = Field(
        ..., max_length=500, min_length=1, pattern='^[a-zA-Z0-9_.\\[\\]-]+$'
    )
    type: Literal['string', 'number', 'boolean', 'json']


class DataSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['fixture']
    fixtureId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    params: dict[str, str | float | bool] | None = {}


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    role: str = Field(..., min_length=1)
    action: str = Field(..., min_length=1)
    expectedResult: str | None = None


class Assertion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    description: str = Field(..., min_length=1)
    kind: Literal[
        'ui.text',
        'ui.element',
        'ui.state',
        'data.value',
        'api.response',
        'download.content',
        'visual',
    ]
    required: bool | None = True
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    operator: Literal[
        'equals',
        'notEquals',
        'contains',
        'notContains',
        'gt',
        'gte',
        'lt',
        'lte',
        'matches',
        'exists',
        'notExists',
    ]
    expected: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class TestCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    roles: list[Role] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step] = Field(..., min_length=1)
    assertions: list[Assertion] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    approvalStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    approvalHash: str | None = Field(None, min_length=1)
    createdAt: AwareDatetime


class Binding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetRef: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator | Locator1 | Locator2 | Locator3
    observedUrl: str = Field(..., min_length=1)
    observedAt: AwareDatetime
    evidenceId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    note: str | None = None


class Observation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environmentId: str
    environmentRevision: int
    bindings: list[Binding] = Field(..., max_length=1200)
    pages: list[Page] = Field(..., max_length=12)


class PlanProposalInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    testCase: TestCase
    observation: Observation
    promptVersion: Literal['planner-v3']


class Actions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['goto']
    path: str | None = None
    pathTemplate: str | None = None


class Value1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['dataRef']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Value3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['credential']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Actions1(BaseModel):
    """
    存在自动保存的字段必须标 effect=WRITE（PRD §7.2 注）
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['fill']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )
    value: Value | Value1 | Value2 | Value3


class Actions2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['click']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )


class Actions4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['switchRole']
    role: str = Field(..., min_length=1)


class Actions5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['captureValue']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )
    saveAs: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')


class Actions6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['assert']
    assertionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class PlanProposalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: PlanProposalInput


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    kind: Literal['heading', 'paragraph', 'table', 'listItem', 'image']
    text: str
    page: int | None = None
    imageStorageKey: str | None = None


class Span(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator4 | Locator5 | Locator6 | Locator7 | Locator8 | Locator9
    quotedText: str | None
    extractionQuality: Literal['GOOD', 'LOW', 'UNPARSED'] | None = 'GOOD'


class ParsedDocumentBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    parseStatus: Literal['PENDING', 'PARSING', 'PARSED', 'FAILED', 'NEEDS_OCR']
    parserVersion: str = Field(..., min_length=1)
    blocks: list[Block]
    spans: list[Span]
    coverageSummary: CoverageSummary
    warnings: list[str] | None = []


class Image(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    storageKey: str
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class RuleExtractionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    projectGlossary: list[ProjectGlossaryItem] | None = Field([], validate_default=True)
    documentVersions: list[ParsedDocumentBundle] = Field(..., min_length=1)
    images: list[Image] | None = Field([], validate_default=True)
    promptVersion: str = Field(..., min_length=1)


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sourceSpanIds: list[RequestId] = Field(..., min_length=1)


class RuleDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., pattern='^rule-draft-\\d{2,}$')
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = None
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[BusinessField] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[str] | None = []


class UnparsedRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: Literal['TABLE_DEGRADED', 'LOW_QUALITY_IMAGE', 'IRRELEVANT', 'OTHER']


class RuleExtractionOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleDrafts: list[RuleDraft]
    clarifications: list[Clarification]
    unparsedRanges: list[UnparsedRange]


class ApprovedRuleVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = Field(None, min_length=1)
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[Items] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[RequestId] | None = Field([], validate_default=True)
    reviewStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    reviewedBy: str | None = None
    reviewedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class ClarificationSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    question: str = Field(..., min_length=1)
    answer: str | None = None
    answerSource: str | None = None
    resolvedBy: str | None = None
    resolvedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class CaseGenerationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvedRuleVersions: list[ApprovedRuleVersion] = Field(..., min_length=1)
    clarificationSources: list[ClarificationSource] | None = Field(
        [], validate_default=True
    )
    roles: list[Role] = Field(..., min_length=1)
    fixtureCapabilities: list[RequestId] | None = Field([], validate_default=True)
    executorCapabilities: list[str] | None = []
    promptVersion: str = Field(..., min_length=1)


class CoverageMapItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseCount: int
    dimensionsCovered: list[str]


class BlockedRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: Literal[
        'MISSING_LOGIN',
        'MISSING_FIXTURE',
        'INSUFFICIENT_INFO',
        'OUT_OF_EXECUTOR_CAPABILITY',
    ]
    detail: str = Field(..., min_length=1)


class DocumentParseInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    storageKey: str = Field(..., min_length=1)
    checksum: str = Field(..., pattern='^[a-f0-9]{64}$')
    fileSizeBytes: int = Field(..., ge=1, le=20971520)


class DocumentParseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: DocumentParseInput


class RuleExtractionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: RuleExtractionInput


class CaseGenerationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: CaseGenerationInput


class InvocationRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal[
        'RULE_EXTRACTION',
        'CASE_GENERATION',
        'VISION_DESCRIBE',
        'PLAN_PROPOSAL',
        'SOURCE_CLASSIFICATION',
        'GOAL_PROPOSAL',
    ]
    promptVersion: str = Field(..., min_length=1)
    response: ModelResponse


class SourceComparisonInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    oldBundle: ParsedDocumentBundle
    newBundle: ParsedDocumentBundle


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class AffectedRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: str = Field(..., min_length=1)
    evidenceRefs: list[EvidenceRef] = Field(..., min_length=1)
    suggestion: str = Field(..., min_length=1)


class AffectedCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    viaRuleVersionIds: list[RequestId] = Field(..., min_length=1)
    reason: Literal['RULE_SOURCE_CHANGED']
    suggestion: str = Field(..., min_length=1)


class ImpactAnalysisOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    affectedRules: list[AffectedRule]
    affectedCases: list[AffectedCase]
    unresolved: list[UnresolvedItem]
    requiresHumanReview: Literal[True]


class SpanSlice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceSpanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    startOffset: int = Field(..., ge=0)
    endOffset: int = Field(..., ge=0)
    sliceId: str = Field(..., min_length=1)


class SpanRefs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['span']
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class SpanRefs1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['slice']
    slice: SpanSlice


class DocumentChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chunkId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    seq: int = Field(..., ge=0)
    boundary: Literal['heading', 'paragraph', 'table', 'fixed-size', 'page']
    text: str
    contextOverlap: str | None = ''
    spanRefs: list[SpanRefs | SpanRefs1]
    isTableContinuation: bool | None = False
    estimatedChars: int = Field(..., ge=0)


class ChunkManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    strategyVersion: Literal['chunk-v1']
    documentChecksum: str
    strategyParams: StrategyParams
    chunks: list[DocumentChunk] = Field(..., max_length=1000, min_length=1)
    totalCodePoints: int = Field(..., ge=0)
    createdAt: AwareDatetime


class Assignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fragmentId: str
    assignment: Literal['processed', 'context', 'blocked']
    chunkId: RequestId | None
    reason: str | None = None


class ChunkCoverageReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    chunkManifestChecksum: str
    totalFragments: int = Field(..., ge=0)
    processedFragments: int = Field(..., ge=0)
    contextFragments: int = Field(..., ge=0)
    blockedFragments: int = Field(..., ge=0)
    assignments: list[Assignment]


class Input(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bundle: ParsedDocumentBundle
    documentChecksum: str = Field(..., min_length=8)
    strategyParams: StrategyParams


class ChunkingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: Input


class Output(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest: ChunkManifest
    coverage: ChunkCoverageReport


class Assertion1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    kind: Literal['deterministic']
    fact: str = Field(..., max_length=500, min_length=1)
    observationType: Literal[
        'ui_text', 'ui_visible', 'api_field', 'api_status', 'db_value'
    ]
    observationRef: str = Field(..., max_length=300, min_length=1)
    operator: Literal[
        'equals',
        'not_equals',
        'greater_than',
        'less_than',
        'exists',
        'not_exists',
        'visible',
        'hidden',
    ]
    expected: Expected | bool | Expected1 | None
    precondition: Precondition | None = None
    unit: Unit | None = None
    tolerance: Field0 | None = None
    allowedRoles: list[AllowedRole] | None = Field(
        [], max_length=20, validate_default=True
    )
    required: bool | None = True


class SemanticCandidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    kind: Literal['semantic_candidate']
    description: str = Field(..., max_length=2000, min_length=1)
    expected: None


class CoverageDeclaration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    dimension: Literal[
        'normal', 'boundary', 'permission', 'multi_role', 'state', 'persistence'
    ]
    status: Literal['planned', 'blocked', 'not_applicable']
    reason: str = Field(..., max_length=2000, min_length=1)


class V2OracleSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleVersionIds: list[RequestId] = Field(..., max_length=500, min_length=1)
    assertions: list[Assertion1] = Field(..., max_length=2000, min_length=1)
    semanticCandidates: list[SemanticCandidate] | None = Field(
        [], max_length=500, validate_default=True
    )
    coverageDeclarations: list[CoverageDeclaration] | None = Field(
        [], max_length=3000, validate_default=True
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    status: Literal['DRAFT', 'APPROVED', 'SUPERSEDED'] | None = 'DRAFT'
    oracleHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    supersedesId: RequestId | None = None
    createdBy: str
    createdAt: AwareDatetime
    approvedBy: str | None = None
    approvedAt: AwareDatetime | None = None


class InputSchemaModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['object', 'string', 'number', 'integer', 'boolean', 'array']
    properties: dict[str, InputSchema] | None = None
    required: list[RequiredItem] | None = Field(None, max_length=100)
    additionalProperties: Literal[False] | None = None
    items: InputSchema | None = None
    minLength: int | None = Field(None, ge=0, le=1000000)
    maxLength: int | None = Field(None, ge=1, le=10000000)
    minimum: float | None = None
    maximum: float | None = None
    enum: list[str | float | bool] | None = Field(None, max_length=1000)
    pattern: str | None = Field(None, max_length=500)
    nullable: bool | None = None


class V2CapabilityManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-z][a-z0-9_-]*(\\.[a-z][a-z0-9_-]*)+$')
    version: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d+$')
    protocolVersion: Literal['aiqa.capability/2']
    protocol: Literal['local-ts', 'remote-http']
    entrypointRef: str = Field(..., max_length=500, min_length=1)
    inputSchema: InputSchemaModel
    outputSchema: InputSchema
    effectClass: Literal['READ', 'WRITE', 'CREATE', 'DELETE']
    permissions: Permissions
    idempotency: Literal['read_only', 'idempotent', 'reconcilable', 'unsafe_retry']
    recovery: Literal['read_only', 'idempotent', 'reconcilable', 'unsafe_retry']
    cancel: Literal['cooperative', 'best_effort', 'unknown']
    timeoutMsMax: int = Field(..., ge=1000, le=600000)
    humanName: str = Field(..., max_length=200, min_length=1)
    description: str | None = Field('', max_length=2000)


class Authorization(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    grantedBy: str
    grantedAt: AwareDatetime
    scope: list[ScopeItem] = Field(..., max_length=50)
    revokedBy: str | None = None
    revokedAt: AwareDatetime | None = None


class V2AdapterInstallation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    capabilityId: str
    capabilityVersion: str
    manifestHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    installedBy: str
    installedAt: AwareDatetime
    status: Literal['PENDING_CHECK', 'VALIDATED', 'AUTHORIZED', 'REVOKED', 'DISABLED']
    endpoint: AnyUrl | None = None
    authorization: Authorization | None = None


class Capability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilityId: str
    version: str
    installationId: RequestId | None = None


class V2HarnessProfileVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[Capability] = Field(..., max_length=200, min_length=1)
    modelRoutes: ModelRoutes
    verifierPolicy: str = Field(..., max_length=200, min_length=1)
    memoryPolicy: str = Field(..., max_length=200, min_length=1)
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    key: str = Field(..., pattern='^[a-z][a-z0-9-]*$')
    version: int = Field(..., ge=1)
    status: (
        Literal['DRAFT', 'VALIDATED', 'PUBLISHED', 'DEPRECATED', 'DISABLED'] | None
    ) = 'DRAFT'
    contentHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    createdBy: str
    createdAt: AwareDatetime
    publishedAt: AwareDatetime | None = None


class Bindings1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['input']
    path: str = Field(
        ..., max_length=500, min_length=1, pattern='^[a-zA-Z0-9_.\\[\\]-]+$'
    )
    type: Literal['string', 'number', 'boolean', 'json']


class Bindings2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['constant']
    value: str | float | bool
    type: Literal['string', 'number', 'boolean', 'json']


class Subflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    definitionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)


class V2ExecutionSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    goal: str = Field(..., max_length=4000, min_length=1)
    oracleSpecId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    oracleHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    profileId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    profileHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    definitionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    definitionVersion: int = Field(..., ge=1)
    workflowRunId: RequestId | None = None
    environmentId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    buildId: str = Field(..., max_length=200, min_length=1)
    status: (
        Literal[
            'QUEUED',
            'PREPARING',
            'RUNNING',
            'WAITING_HUMAN',
            'WAITING_AUTH',
            'PAUSED',
            'COMPLETED',
            'FAILED',
            'CANCELLED',
        ]
        | None
    ) = 'QUEUED'
    budget: V2SessionBudget
    usage: V2SessionUsage
    terminationReason: TerminationReason | None = None
    cancelRequestedAt: AwareDatetime | None = None
    pauseRequestedAt: AwareDatetime | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class V2ActionIntent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sessionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    stepAttemptId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    capabilityId: str
    capabilityVersion: str
    inputHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    idempotencyKey: str = Field(..., max_length=200, min_length=8)
    fencingToken: str = Field(..., max_length=128, min_length=1)
    deadline: AwareDatetime
    createdAt: AwareDatetime


class V2EffectReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    intentId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    outcome: Literal['succeeded', 'failed', 'unknown_write', 'cancelled']
    resourceKeys: list[ResourceKey] | None = Field(
        [], max_length=100, validate_default=True
    )
    externalRefs: list[ExternalRef] | None = Field(
        [], max_length=100, validate_default=True
    )
    outputHash: OutputHash | None = None
    recordedAt: AwareDatetime


class V2Invocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    intentId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    attemptNo: int = Field(..., ge=1, le=10)
    status: (
        Literal[
            'PENDING',
            'CLAIMED',
            'RUNNING',
            'SUCCEEDED',
            'FAILED',
            'CANCELLED',
            'UNKNOWN',
        ]
        | None
    ) = 'PENDING'
    businessOutcome: (
        Literal['pass', 'fail', 'blocked', 'review', 'not_evaluated', 'unknown'] | None
    ) = None
    receipt: V2EffectReceipt | None = None
    error: Error | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class V2ObservationSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sessionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    round: int = Field(..., ge=1)
    source: Literal['page', 'api', 'tool', 'model']
    observedUrl: AnyUrl | None = None
    evidenceArtifactIds: list[RequestId] | None = Field(
        [], max_length=200, validate_default=True
    )
    summary: dict[str, Any]
    observedAt: AwareDatetime


class Selection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal[
        'span', 'rule', 'page_clue', 'api_clue', 'memory', 'conflict', 'unparsed_range'
    ]
    ref: str = Field(..., max_length=500, min_length=1)
    documentVersionId: RequestId | None = None
    score: Score | None = None
    decision: Literal['selected', 'rejected']
    reason: str = Field(..., max_length=2000, min_length=1)


class V2ContextManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sessionId: RequestId | None = None
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    retrievalStrategy: str = Field(..., max_length=200, min_length=1)
    selections: list[Selection] = Field(..., max_length=5000, min_length=1)
    budget: Budget
    inputHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    generatedAt: AwareDatetime


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    dimension: Literal[
        'normal', 'boundary', 'permission', 'multi_role', 'state', 'persistence'
    ]
    status: Literal['covered', 'blocked', 'not_applicable', 'not_evaluated']
    evidenceAttemptId: RequestId | None = None
    reason: str = Field(..., max_length=2000, min_length=1)
    confirmedBy: str | None = None


class V2CoverageLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    oracleSpecId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    entries: list[Entry] = Field(..., max_length=6000, min_length=1)
    updatedAt: AwareDatetime


class FirstFailure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sessionId: RequestId | None = None
    attemptId: RequestId | None = None
    runId: RequestId | None = None
    evidenceIds: list[RequestId] | None = Field(
        [], max_length=100, validate_default=True
    )
    observedAt: AwareDatetime


class MinimalReproduction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    steps: list[Step2] = Field(..., max_length=100, min_length=1)
    resourceKeys: list[ResourceKey] | None = Field(
        [], max_length=100, validate_default=True
    )
    verifiedAt: AwareDatetime | None = None


class V2Finding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    oracleSpecId: RequestId | None = None
    ruleVersionId: RequestId | None = None
    status: (
        Literal[
            'candidate',
            'reproduced',
            'human_confirmed',
            'investigating',
            'fix_verified',
            'rejected',
        ]
        | None
    ) = 'candidate'
    expected: str = Field(..., max_length=4000, min_length=1)
    actual: str = Field(..., max_length=4000, min_length=1)
    firstFailure: FirstFailure
    hypotheses: list[Hypothes] | None = Field([], max_length=50, validate_default=True)
    minimalReproduction: MinimalReproduction | None = None
    severity: Severity | None = None
    dedupeKey: str = Field(..., max_length=300, min_length=8)
    buildId: str = Field(..., max_length=200, min_length=1)
    role: Role3 | None = None
    createdAt: AwareDatetime


class V2MemoryUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    memoryRecordId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sessionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    retrieved: Literal[True]
    decision: Literal['used', 'rejected']
    reason: str = Field(..., max_length=2000, min_length=1)
    outcome: Literal['helped', 'neutral', 'harmful', 'unknown'] | None = None
    usedAt: AwareDatetime


class Execution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ranAt: AwareDatetime | None = None
    totalTests: TotalTests | None = None
    failedTests: FailedTests | None = None
    reportArtifactId: RequestId | None = None


class V2TestPatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    origin: Origin1
    repositoryUrl: AnyUrl
    commitSha: str = Field(..., pattern='^[a-f0-9]{40}$')
    files: list[File2] = Field(..., max_length=500, min_length=1)
    status: Literal['draft', 'executed', 'validated', 'rejected'] | None = 'draft'
    execution: Execution
    validity: Validity
    createdAt: AwareDatetime


class V2EvaluationTrial(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    campaignId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    flowId: str = Field(..., max_length=300, min_length=1)
    sessionId: RequestId | None = None
    firstResult: Literal[
        'pass_correct',
        'fail_correct',
        'false_positive',
        'false_negative',
        'blocked',
        'error',
        'unknown',
    ]
    finalResult: Literal[
        'pass_correct',
        'fail_correct',
        'false_positive',
        'false_negative',
        'blocked',
        'error',
        'unknown',
    ]
    humanInterventionMinutes: HumanInterventionMinutes | None = None
    costMicros: CostMicros | None = None
    latencyMs: int = Field(..., ge=0)
    ranAt: AwareDatetime


class V2CapabilityRpcEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocolVersion: Literal['aiqa.capability-rpc/2']
    invocationId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    deadline: AwareDatetime
    idempotencyKey: str = Field(..., max_length=200, min_length=8)


class V2RemoteExecuteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    envelope: V2CapabilityRpcEnvelope
    input: Any | None = None


class RuleRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sourceSpanIds: list[RequestId] = Field(..., min_length=1)


class ContextRetrievalInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: str = Field(..., max_length=4000, min_length=1)
    documentVersions: list[ParsedDocumentBundle] = Field(
        ..., max_length=50, min_length=1
    )
    ruleRefs: list[RuleRef] | None = Field([], max_length=500, validate_default=True)
    maxSelected: int | None = Field(50, ge=1, le=500)


class Selection1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['span', 'unparsed_range']
    ref: str = Field(..., max_length=500, min_length=1)
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    score: Score1 | None
    decision: Literal['selected', 'rejected']
    reason: str = Field(..., max_length=2000, min_length=1)


class ContextRetrievalOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: str = Field(..., max_length=200, min_length=1)
    selections: list[Selection1] = Field(..., max_length=10000, min_length=1)


class OldFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., max_length=1024, min_length=1)
    bundle: ParsedDocumentBundle
    fileChecksum: str = Field(..., pattern='^[a-f0-9]{64}$')


class GoalProposalAgentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: GoalProposalAgentInput


class SnapshotFileEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., max_length=1024, min_length=1)
    checksum: Checksum | None
    sizeBytes: SizeBytes | None
    documentVersionId: RequestId | None
    format: (
        Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
        | None
    )
    fetchStatus: Literal['OK', 'NOT_FETCHED', 'FETCH_FAILED']
    parseStatus: Literal['PENDING', 'PARSING', 'PARSED', 'FAILED', 'NEEDS_OCR'] | None


class Scope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: Literal[''] | PathModel
    include: list[PathModel] = Field(..., max_length=100, min_length=1)
    exclude: list[PathModel] = Field(..., max_length=100)
    policyVersion: str = Field(..., max_length=100, min_length=1)


class RepositorySnapshotManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshotId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    repositoryId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    commitSha: str = Field(..., pattern='^[a-f0-9]{40}$')
    scope: Scope
    enumerationStatus: Literal['COMPLETE', 'PARTIAL', 'FAILED']
    enumerationReason: EnumerationReason | None
    entries: list[SnapshotFileEntry] = Field(..., max_length=200)


class SnapshotDiffInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldSnapshot: RepositorySnapshotManifest
    newSnapshot: RepositorySnapshotManifest
    bundles: dict[str, ParsedDocumentBundle]


class ItemsModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = Field(None, min_length=1)
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[Items] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[RequestId] | None = Field([], validate_default=True)
    reviewStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    reviewedBy: str | None = None
    reviewedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class ItemsModel1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., max_length=1024, min_length=1)
    bundle: ParsedDocumentBundle
    fileChecksum: str = Field(..., pattern='^[a-f0-9]{64}$')


class ItemsModel2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator10 | Locator11 | Locator12 | Locator13 | Locator14 | Locator15
    quotedText: str | None
    extractionQuality: Literal['GOOD', 'LOW', 'UNPARSED'] | None = 'GOOD'


class Assertion2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    description: str = Field(..., min_length=1)
    kind: Literal[
        'ui.text',
        'ui.element',
        'ui.state',
        'data.value',
        'api.response',
        'download.content',
        'visual',
    ]
    required: bool | None = True
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    operator: Literal[
        'equals',
        'notEquals',
        'contains',
        'notContains',
        'gt',
        'gte',
        'lt',
        'lte',
        'matches',
        'exists',
        'notExists',
    ]
    expected: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class TestCaseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    roles: list[Role4] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step] = Field(..., min_length=1)
    assertions: list[Assertion2] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    approvalStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    approvalHash: str | None = Field(None, min_length=1)
    createdAt: AwareDatetime


class ItemsModel3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    description: str = Field(..., min_length=1)
    kind: Literal[
        'ui.text',
        'ui.element',
        'ui.state',
        'data.value',
        'api.response',
        'download.content',
        'visual',
    ]
    required: bool | None = True
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    operator: Literal[
        'equals',
        'notEquals',
        'contains',
        'notContains',
        'gt',
        'gte',
        'lt',
        'lte',
        'matches',
        'exists',
        'notExists',
    ]
    expected: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class Value5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['dataRef']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Value7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['credential']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class AdditionalProperties2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['input']
    path: str = Field(
        ..., max_length=500, min_length=1, pattern='^[a-zA-Z0-9_.\\[\\]-]+$'
    )
    type: Literal['string', 'number', 'boolean', 'json']


class AdditionalProperties3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['constant']
    value: str | float | bool
    type: Literal['string', 'number', 'boolean', 'json']


class AdditionalProperties(
    RootModel[AdditionalProperties1 | AdditionalProperties2 | AdditionalProperties3]
):
    root: AdditionalProperties1 | AdditionalProperties2 | AdditionalProperties3


class Condition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    left: AdditionalProperties1 | AdditionalProperties2 | AdditionalProperties3
    operator: Literal['eq', 'ne', 'gt', 'lt', 'exists', 'not_exists']
    right: (
        AdditionalProperties1 | AdditionalProperties2 | AdditionalProperties3 | None
    ) = None
    onUnknown: Literal['skip', 'fail', 'require_human']


class SourceClassificationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: SourceClassificationOutput


class Actions3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['select']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )
    value: Value4 | Value5 | Value6 | Value7


class PlanProposalOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[
        Actions | Actions1 | Actions2 | Actions3 | Actions4 | Actions5 | Actions6
    ] = Field(..., max_length=100)
    targets: list[Target]
    blockedReasons: list[str] | None = []


class PlanProposalResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: PlanProposalOutput


class CaseDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    roles: list[Role] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step1] = Field(..., min_length=1)
    assertions: list[ItemsModel3] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    dimensions: list[
        Literal[
            'HAPPY_PATH',
            'INVALID_INPUT',
            'BOUNDARY',
            'PERMISSION',
            'STATE',
            'CROSS_MODULE',
            'PERSISTENCE',
        ]
    ] = Field(..., min_length=1)


class CaseGenerationOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseDrafts: list[CaseDraft]
    coverageMap: list[CoverageMapItem]
    blockedRequirements: list[BlockedRequirement]


class DocumentParseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: ParsedDocumentBundle


class RuleExtractionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: RuleExtractionOutput


class CaseGenerationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: CaseGenerationOutput


class SourceChange1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['added']
    old: None
    new: ItemsModel2
    reason: None


class SourceChange2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['removed']
    old: ItemsModel2
    new: None
    reason: None


class SourceChange3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['modified']
    old: ItemsModel2
    new: ItemsModel2
    reason: None


class SourceChange4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['uncertain']
    old: ItemsModel2
    new: ItemsModel2 | None
    reason: str = Field(..., min_length=1)


class SourceChangeReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    oldDocumentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    newDocumentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    changes: list[SourceChange1 | SourceChange2 | SourceChange3 | SourceChange4] = (
        Field(..., max_length=40000)
    )


class ImpactAnalysisInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceReports: list[SourceChangeReport] = Field(..., max_length=100)
    approvedRuleVersions: list[ItemsModel]
    approvedCaseVersions: list[TestCaseModel]


class ChangeReviewAnalysisInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comparison: SourceComparisonInput
    approvedRuleVersions: list[ItemsModel] = Field(..., max_length=500)
    approvedCaseVersions: list[TestCaseModel] = Field(..., max_length=500)


class ChangeReviewAnalysisOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceReport: SourceChangeReport
    impact: ImpactAnalysisOutput


class ChangeReviewAnalysisRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: ChangeReviewAnalysisInput


class ChangeReviewAnalysisResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: ChangeReviewAnalysisOutput


class ChunkingResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: Output


class Repeat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxIterations: int = Field(..., ge=1, le=1000)
    exitWhen: Condition | None = None


class Map(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputSet: AdditionalProperties1 | AdditionalProperties2 | AdditionalProperties3
    maxItems: int = Field(..., ge=1, le=10000)
    maxConcurrency: int = Field(..., ge=1, le=2)


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodeId: str = Field(..., pattern='^[a-z][a-z0-9-]*$')
    capabilityId: str = Field(..., max_length=200, min_length=1)
    capabilityVersion: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d+$')
    dependsOn: list[DependsOnItem] | None = Field(
        [], max_length=100, validate_default=True
    )
    bindings: (
        dict[constr(min_length=1, max_length=200), Bindings | Bindings1 | Bindings2]
        | None
    ) = Field({}, validate_default=True)
    condition: Condition | None = None
    retry: Retry | None = None
    repeat: Repeat | None = None
    map: Map | None = None
    subflow: Subflow | None = None
    onFailure: Literal['fail', 'skip', 'require_human'] | None = 'fail'


class V2WorkflowDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=200, min_length=1)
    description: str | None = Field('', max_length=2000)
    nodes: list[Node] = Field(..., max_length=200, min_length=1)
    maxSubflowDepth: int | None = Field(4, ge=1, le=8)
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    projectId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    status: Literal['DRAFT', 'PUBLISHED', 'DEPRECATED'] | None = 'DRAFT'
    astHash: str = Field(..., pattern='^[a-f0-9]{64}$')
    createdBy: str
    createdAt: AwareDatetime
    publishedAt: AwareDatetime | None = None


class ContextRetrievalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: ContextRetrievalInput


class ContextRetrievalResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: ContextRetrievalOutput


class MultiFileComparisonInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldFiles: list[OldFile] = Field(..., max_length=200, min_length=1)
    newFiles: list[ItemsModel1] = Field(..., max_length=200, min_length=1)
    excludedPaths: list[ExcludedPath] | None = Field(
        [], max_length=200, validate_default=True
    )


class Outcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['unchanged', 'modified', 'added', 'removed', 'renamed', 'uncertain']
    oldPath: OldPath | None
    newPath: NewPath | None
    contentHash: str | None
    fragmentReport: SourceChangeReport | None
    reason: str | None


class MultiFileChangeReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcomes: list[Outcome] = Field(..., max_length=400, min_length=1)
    totals: Totals
    excludedPaths: list[ExcludedPath] | None = Field(
        [], max_length=200, validate_default=True
    )
    exclusionsChanged: bool
    truncated: bool


class SnapshotCompareRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: SnapshotDiffInput


class GoalProposalAgentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: GoalProposalAgentOutput


class SnapshotFileChange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['unchanged', 'added', 'removed', 'modified', 'renamed', 'uncertain']
    old: SnapshotFileEntry | None
    new: SnapshotFileEntry | None
    reasonCode: (
        Literal[
            'SNAPSHOT_INCOMPLETE',
            'FETCH_UNAVAILABLE',
            'PARSE_UNAVAILABLE',
            'SOURCE_QUALITY_UNCERTAIN',
            'FORMAT_CHANGED',
            'PARSE_CHANGED',
            'AMBIGUOUS_RENAME',
        ]
        | None
    )
    reason: Reason | None
    spanReport: SourceChangeReport | None


class SnapshotDiffReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldSnapshotId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    newSnapshotId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    fileChanges: list[SnapshotFileChange] = Field(..., max_length=400)
    complete: bool
    requiresHumanReview: Literal[True]
    coverage: Coverage


class SnapshotCompareResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: SnapshotDiffReport


class IntelligenceContracts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    SourceClassificationInput_1: SourceClassificationInput = Field(
        ..., alias='SourceClassificationInput'
    )
    SourceClassificationOutput_1: SourceClassificationOutput = Field(
        ..., alias='SourceClassificationOutput'
    )
    SourceClassificationRequest_1: SourceClassificationRequest = Field(
        ..., alias='SourceClassificationRequest'
    )
    SourceClassificationResponse_1: SourceClassificationResponse = Field(
        ..., alias='SourceClassificationResponse'
    )
    PlanProposalInput_1: PlanProposalInput = Field(..., alias='PlanProposalInput')
    PlanProposalOutput_1: PlanProposalOutput = Field(..., alias='PlanProposalOutput')
    PlanProposalRequest_1: PlanProposalRequest = Field(..., alias='PlanProposalRequest')
    PlanProposalResponse_1: PlanProposalResponse = Field(
        ..., alias='PlanProposalResponse'
    )
    ParsedDocumentBundle_1: ParsedDocumentBundle = Field(
        ..., alias='ParsedDocumentBundle'
    )
    RuleExtractionInput_1: RuleExtractionInput = Field(..., alias='RuleExtractionInput')
    RuleExtractionOutput_1: RuleExtractionOutput = Field(
        ..., alias='RuleExtractionOutput'
    )
    CaseGenerationInput_1: CaseGenerationInput = Field(..., alias='CaseGenerationInput')
    CaseGenerationOutput_1: CaseGenerationOutput = Field(
        ..., alias='CaseGenerationOutput'
    )
    ModelResponse_1: ModelResponse = Field(..., alias='ModelResponse')
    TextModelRequest_1: TextModelRequest = Field(..., alias='TextModelRequest')
    VisionModelRequest_1: VisionModelRequest = Field(..., alias='VisionModelRequest')
    DocumentParseInput_1: DocumentParseInput = Field(..., alias='DocumentParseInput')
    DocumentParseRequest_1: DocumentParseRequest = Field(
        ..., alias='DocumentParseRequest'
    )
    DocumentParseResponse_1: DocumentParseResponse = Field(
        ..., alias='DocumentParseResponse'
    )
    RuleExtractionRequest_1: RuleExtractionRequest = Field(
        ..., alias='RuleExtractionRequest'
    )
    RuleExtractionResponse_1: RuleExtractionResponse = Field(
        ..., alias='RuleExtractionResponse'
    )
    CaseGenerationRequest_1: CaseGenerationRequest = Field(
        ..., alias='CaseGenerationRequest'
    )
    CaseGenerationResponse_1: CaseGenerationResponse = Field(
        ..., alias='CaseGenerationResponse'
    )
    InvocationRecord_1: InvocationRecord = Field(..., alias='InvocationRecord')
    SourceChange: SourceChange1 | SourceChange2 | SourceChange3 | SourceChange4
    SourceComparisonInput_1: SourceComparisonInput = Field(
        ..., alias='SourceComparisonInput'
    )
    SourceChangeReport_1: SourceChangeReport = Field(..., alias='SourceChangeReport')
    ImpactAnalysisInput_1: ImpactAnalysisInput = Field(..., alias='ImpactAnalysisInput')
    ImpactAnalysisOutput_1: ImpactAnalysisOutput = Field(
        ..., alias='ImpactAnalysisOutput'
    )
    ChangeReviewAnalysisInput_1: ChangeReviewAnalysisInput = Field(
        ..., alias='ChangeReviewAnalysisInput'
    )
    ChangeReviewAnalysisOutput_1: ChangeReviewAnalysisOutput = Field(
        ..., alias='ChangeReviewAnalysisOutput'
    )
    ChangeReviewAnalysisRequest_1: ChangeReviewAnalysisRequest = Field(
        ..., alias='ChangeReviewAnalysisRequest'
    )
    ChangeReviewAnalysisResponse_1: ChangeReviewAnalysisResponse = Field(
        ..., alias='ChangeReviewAnalysisResponse'
    )
    SpanSlice_1: SpanSlice = Field(..., alias='SpanSlice')
    DocumentChunk_1: DocumentChunk = Field(..., alias='DocumentChunk')
    ChunkManifest_1: ChunkManifest = Field(..., alias='ChunkManifest')
    ChunkCoverageReport_1: ChunkCoverageReport = Field(..., alias='ChunkCoverageReport')
    ChunkingRequest_1: ChunkingRequest = Field(..., alias='ChunkingRequest')
    ChunkingResponse_1: ChunkingResponse = Field(..., alias='ChunkingResponse')
    V2OracleSpec_1: V2OracleSpec = Field(..., alias='V2OracleSpec')
    V2CapabilityManifest_1: V2CapabilityManifest = Field(
        ..., alias='V2CapabilityManifest'
    )
    V2AdapterInstallation_1: V2AdapterInstallation = Field(
        ..., alias='V2AdapterInstallation'
    )
    V2HarnessProfileVersion_1: V2HarnessProfileVersion = Field(
        ..., alias='V2HarnessProfileVersion'
    )
    V2WorkflowDefinition_1: V2WorkflowDefinition = Field(
        ..., alias='V2WorkflowDefinition'
    )
    V2ExecutionSession_1: V2ExecutionSession = Field(..., alias='V2ExecutionSession')
    V2SessionBudget_1: V2SessionBudget = Field(..., alias='V2SessionBudget')
    V2SessionUsage_1: V2SessionUsage = Field(..., alias='V2SessionUsage')
    V2ActionIntent_1: V2ActionIntent = Field(..., alias='V2ActionIntent')
    V2EffectReceipt_1: V2EffectReceipt = Field(..., alias='V2EffectReceipt')
    V2Invocation_1: V2Invocation = Field(..., alias='V2Invocation')
    V2ObservationSnapshot_1: V2ObservationSnapshot = Field(
        ..., alias='V2ObservationSnapshot'
    )
    V2ContextManifest_1: V2ContextManifest = Field(..., alias='V2ContextManifest')
    V2CoverageLedger_1: V2CoverageLedger = Field(..., alias='V2CoverageLedger')
    V2Finding_1: V2Finding = Field(..., alias='V2Finding')
    V2MemoryUsage_1: V2MemoryUsage = Field(..., alias='V2MemoryUsage')
    V2TestPatch_1: V2TestPatch = Field(..., alias='V2TestPatch')
    V2EvaluationTrial_1: V2EvaluationTrial = Field(..., alias='V2EvaluationTrial')
    V2CapabilityRpcEnvelope_1: V2CapabilityRpcEnvelope = Field(
        ..., alias='V2CapabilityRpcEnvelope'
    )
    V2RemoteExecuteRequest_1: V2RemoteExecuteRequest = Field(
        ..., alias='V2RemoteExecuteRequest'
    )
    V2RemoteCapabilityResult_1: V2RemoteCapabilityResult = Field(
        ..., alias='V2RemoteCapabilityResult'
    )
    ContextRetrievalRequest_1: ContextRetrievalRequest = Field(
        ..., alias='ContextRetrievalRequest'
    )
    ContextRetrievalResponse_1: ContextRetrievalResponse = Field(
        ..., alias='ContextRetrievalResponse'
    )
    ContextRetrievalInput_1: ContextRetrievalInput = Field(
        ..., alias='ContextRetrievalInput'
    )
    ContextRetrievalOutput_1: ContextRetrievalOutput = Field(
        ..., alias='ContextRetrievalOutput'
    )
    MultiFileComparisonInput_1: MultiFileComparisonInput = Field(
        ..., alias='MultiFileComparisonInput'
    )
    MultiFileChangeReport_1: MultiFileChangeReport = Field(
        ..., alias='MultiFileChangeReport'
    )
    SnapshotCompareRequest_1: SnapshotCompareRequest = Field(
        ..., alias='SnapshotCompareRequest'
    )
    SnapshotCompareResponse_1: SnapshotCompareResponse = Field(
        ..., alias='SnapshotCompareResponse'
    )
    GoalProposalAgentInput_1: GoalProposalAgentInput = Field(
        ..., alias='GoalProposalAgentInput'
    )
    GoalProposalAgentOutput_1: GoalProposalAgentOutput = Field(
        ..., alias='GoalProposalAgentOutput'
    )
    GoalProposalAgentRequest_1: GoalProposalAgentRequest = Field(
        ..., alias='GoalProposalAgentRequest'
    )
    GoalProposalAgentResponse_1: GoalProposalAgentResponse = Field(
        ..., alias='GoalProposalAgentResponse'
    )
    SnapshotFileEntry_1: SnapshotFileEntry = Field(..., alias='SnapshotFileEntry')
    RepositorySnapshotManifest_1: RepositorySnapshotManifest = Field(
        ..., alias='RepositorySnapshotManifest'
    )
    SnapshotDiffInput_1: SnapshotDiffInput = Field(..., alias='SnapshotDiffInput')
    SnapshotFileChange_1: SnapshotFileChange = Field(..., alias='SnapshotFileChange')
    SnapshotDiffReport_1: SnapshotDiffReport = Field(..., alias='SnapshotDiffReport')


class Model(RootModel[IntelligenceContracts]):
    root: IntelligenceContracts


InputSchema.model_rebuild()
