# generated by datamodel-codegen:
#   filename:  schema.v1.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class File(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    format: str
    excerpt: str = Field(..., max_length=2000)


class SourceClassificationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[File] = Field(..., max_length=50)
    promptVersion: Literal['sources-v1']


class File1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    category: Literal[
        'BUSINESS_CANDIDATE',
        'API_CONTRACT',
        'RUNTIME_CLUE',
        'TEST_CLUE',
        'UNCLASSIFIED',
    ]
    reason: str = Field(..., max_length=500, min_length=1)


class SourceClassificationOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[File1] = Field(..., max_length=50)


class SourceClassificationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: SourceClassificationInput


class Role(RootModel[str]):
    root: str = Field(..., min_length=1)


class DataSpec1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['create']
    note: str = Field(..., min_length=1)


class Cleanup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['namespace', 'fixture', 'manual']
    note: str | None = None


class Locator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['testId']
    value: str = Field(..., min_length=1)


class Locator1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['role']
    role: str = Field(..., min_length=1)
    name: str | None = None


class Locator2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['label']
    value: str = Field(..., min_length=1)


class Locator3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    value: str = Field(..., min_length=1)


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str
    url: AnyUrl
    title: str
    text: str = Field(..., max_length=20000)


class OnlyIf(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    varName: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')
    operator: Literal['eq', 'neq', 'gt', 'gte', 'lt', 'lte']
    value: str | float | bool


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['literal']
    value: str


class Value2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['captured']
    varName: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assertionId: str
    targetRef: str


class Locator4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-line']
    startLine: int
    endLine: int


class PathItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class Locator5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-heading']
    path: list[PathItem] = Field(..., min_length=1)


class Locator6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-paragraph']
    paragraphIndex: int


class Locator7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-cell']
    tableIndex: int
    row: int
    col: int


class Locator8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pdf-page']
    page: int = Field(..., ge=1)


class Locator9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['image-region']
    bbox: list[float] = Field(..., max_length=4, min_length=4)


class CoverageSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalBlocks: int
    goodSpans: int
    lowSpans: int
    unparsedSpans: int


class ProjectGlossaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term: str
    definition: str


class BusinessField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., min_length=1)
    operator: (
        Literal['gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'in', 'between', 'contains']
        | None
    ) = None
    value: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class Clarification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleDraftKeys: list[str] = Field(..., min_length=1)
    question: str = Field(..., min_length=1)
    kind: Literal['MISSING_INFO', 'CONFLICT', 'AMBIGUITY']


class Step1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str = Field(..., min_length=1)
    action: str = Field(..., min_length=1)
    expectedResult: str | None = None


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputTokens: int
    outputTokens: int
    estimatedCost: float | None = None


class ModelResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parsedJson: Any | None = None
    rawText: str
    repairsApplied: (
        list[Literal['code-fence', 'trailing-comma', 'truncated-json', 'bom']] | None
    ) = []
    provider: Literal['moonshot', 'mock']
    model: str
    requestId: str | None
    usage: Usage
    latencyMs: int
    outcome: Literal['SUCCESS', 'INVALID_OUTPUT', 'TIMEOUT', 'PROVIDER_ERROR']


class TextModelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal[
        'RULE_EXTRACTION',
        'CASE_GENERATION',
        'VISION_DESCRIBE',
        'PLAN_PROPOSAL',
        'SOURCE_CLASSIFICATION',
    ]
    system: str
    user: str
    outputSchema: Any | None = None
    temperature: float | None = Field(None, ge=0.0, le=1.0)
    maxOutputTokens: int | None = None
    timeoutMs: int = Field(..., ge=1000, le=600000)


class VisionModelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal['VISION_DESCRIBE']
    imageStorageKey: str = Field(..., min_length=1)
    hint: str = Field(..., min_length=1)
    outputSchema: Any | None = None
    timeoutMs: int = Field(..., ge=1000, le=600000)


class UnresolvedItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class StrategyParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxCharsPerChunk: int = Field(..., ge=500, le=50000)
    contextOverlapChars: int = Field(..., ge=0, le=5000)
    modelBudgetChars: int = Field(..., ge=1000, le=200000)


class Locator10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-line']
    startLine: int
    endLine: int


class Locator11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-heading']
    path: list[PathItem] = Field(..., min_length=1)


class Locator12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-paragraph']
    paragraphIndex: int


class Locator13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-cell']
    tableIndex: int
    row: int
    col: int


class Locator14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pdf-page']
    page: int = Field(..., ge=1)


class Locator15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['image-region']
    bbox: list[float] = Field(..., max_length=4, min_length=4)


class Value4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['literal']
    value: str


class Value6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['captured']
    varName: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')


class Items(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., min_length=1)
    operator: (
        Literal['gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'in', 'between', 'contains']
        | None
    ) = None
    value: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class RequestId(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class DataSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['fixture']
    fixtureId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    params: dict[str, str | float | bool] | None = {}


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    role: str = Field(..., min_length=1)
    action: str = Field(..., min_length=1)
    expectedResult: str | None = None


class Assertion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    description: str = Field(..., min_length=1)
    kind: Literal[
        'ui.text',
        'ui.element',
        'ui.state',
        'data.value',
        'api.response',
        'download.content',
        'visual',
    ]
    required: bool | None = True
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    operator: Literal[
        'equals',
        'notEquals',
        'contains',
        'notContains',
        'gt',
        'gte',
        'lt',
        'lte',
        'matches',
        'exists',
        'notExists',
    ]
    expected: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class TestCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    roles: list[Role] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step] = Field(..., min_length=1)
    assertions: list[Assertion] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    approvalStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    approvalHash: str | None = Field(None, min_length=1)
    createdAt: AwareDatetime


class Binding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetRef: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator | Locator1 | Locator2 | Locator3
    observedUrl: str = Field(..., min_length=1)
    observedAt: AwareDatetime
    evidenceId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    note: str | None = None


class Observation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    environmentId: str
    environmentRevision: int
    bindings: list[Binding] = Field(..., max_length=1200)
    pages: list[Page] = Field(..., max_length=12)


class PlanProposalInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    testCase: TestCase
    observation: Observation
    promptVersion: Literal['planner-v3']


class Actions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['goto']
    path: str | None = None
    pathTemplate: str | None = None


class Value1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['dataRef']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Value3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['credential']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Actions1(BaseModel):
    """
    存在自动保存的字段必须标 effect=WRITE（PRD §7.2 注）
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['fill']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )
    value: Value | Value1 | Value2 | Value3


class Actions2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['click']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )


class Actions4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['switchRole']
    role: str = Field(..., min_length=1)


class Actions5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['captureValue']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )
    saveAs: str = Field(..., pattern='^[a-zA-Z][a-zA-Z0-9_]*$')


class Actions6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['assert']
    assertionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class PlanProposalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: PlanProposalInput


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    kind: Literal['heading', 'paragraph', 'table', 'listItem', 'image']
    text: str
    page: int | None = None
    imageStorageKey: str | None = None


class Span(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator4 | Locator5 | Locator6 | Locator7 | Locator8 | Locator9
    quotedText: str | None
    extractionQuality: Literal['GOOD', 'LOW', 'UNPARSED'] | None = 'GOOD'


class ParsedDocumentBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    parseStatus: Literal['PENDING', 'PARSING', 'PARSED', 'FAILED', 'NEEDS_OCR']
    parserVersion: str = Field(..., min_length=1)
    blocks: list[Block]
    spans: list[Span]
    coverageSummary: CoverageSummary
    warnings: list[str] | None = []


class Image(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    storageKey: str
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class RuleExtractionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    projectGlossary: list[ProjectGlossaryItem] | None = Field([], validate_default=True)
    documentVersions: list[ParsedDocumentBundle] = Field(..., min_length=1)
    images: list[Image] | None = Field([], validate_default=True)
    promptVersion: str = Field(..., min_length=1)


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sourceSpanIds: list[RequestId] = Field(..., min_length=1)


class RuleDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., pattern='^rule-draft-\\d{2,}$')
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = None
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[BusinessField] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[str] | None = []


class UnparsedRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: Literal['TABLE_DEGRADED', 'LOW_QUALITY_IMAGE', 'IRRELEVANT', 'OTHER']


class RuleExtractionOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleDrafts: list[RuleDraft]
    clarifications: list[Clarification]
    unparsedRanges: list[UnparsedRange]


class ApprovedRuleVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = Field(None, min_length=1)
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[Items] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[RequestId] | None = Field([], validate_default=True)
    reviewStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    reviewedBy: str | None = None
    reviewedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class ClarificationSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    question: str = Field(..., min_length=1)
    answer: str | None = None
    answerSource: str | None = None
    resolvedBy: str | None = None
    resolvedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class CaseGenerationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvedRuleVersions: list[ApprovedRuleVersion] = Field(..., min_length=1)
    clarificationSources: list[ClarificationSource] | None = Field(
        [], validate_default=True
    )
    roles: list[Role] = Field(..., min_length=1)
    fixtureCapabilities: list[RequestId] | None = Field([], validate_default=True)
    executorCapabilities: list[str] | None = []
    promptVersion: str = Field(..., min_length=1)


class CoverageMapItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseCount: int
    dimensionsCovered: list[str]


class BlockedRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: Literal[
        'MISSING_LOGIN',
        'MISSING_FIXTURE',
        'INSUFFICIENT_INFO',
        'OUT_OF_EXECUTOR_CAPABILITY',
    ]
    detail: str = Field(..., min_length=1)


class DocumentParseInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    storageKey: str = Field(..., min_length=1)
    checksum: str = Field(..., pattern='^[a-f0-9]{64}$')
    fileSizeBytes: int = Field(..., ge=1, le=20971520)


class DocumentParseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: DocumentParseInput


class RuleExtractionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: RuleExtractionInput


class CaseGenerationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: CaseGenerationInput


class InvocationRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal[
        'RULE_EXTRACTION',
        'CASE_GENERATION',
        'VISION_DESCRIBE',
        'PLAN_PROPOSAL',
        'SOURCE_CLASSIFICATION',
    ]
    promptVersion: str = Field(..., min_length=1)
    response: ModelResponse


class SourceComparisonInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    oldBundle: ParsedDocumentBundle
    newBundle: ParsedDocumentBundle


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class AffectedRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: str = Field(..., min_length=1)
    evidenceRefs: list[EvidenceRef] = Field(..., min_length=1)
    suggestion: str = Field(..., min_length=1)


class AffectedCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    viaRuleVersionIds: list[RequestId] = Field(..., min_length=1)
    reason: Literal['RULE_SOURCE_CHANGED']
    suggestion: str = Field(..., min_length=1)


class ImpactAnalysisOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    affectedRules: list[AffectedRule]
    affectedCases: list[AffectedCase]
    unresolved: list[UnresolvedItem]
    requiresHumanReview: Literal[True]


class SpanSlice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceSpanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    startOffset: int = Field(..., ge=0)
    endOffset: int = Field(..., ge=0)
    sliceId: str = Field(..., min_length=1)


class SpanRefs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['span']
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class SpanRefs1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['slice']
    slice: SpanSlice


class DocumentChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chunkId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    seq: int = Field(..., ge=0)
    boundary: Literal['heading', 'paragraph', 'table', 'fixed-size', 'page']
    text: str
    contextOverlap: str | None = ''
    spanRefs: list[SpanRefs | SpanRefs1]
    isTableContinuation: bool | None = False
    estimatedChars: int = Field(..., ge=0)


class ChunkManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    strategyVersion: Literal['chunk-v1']
    documentChecksum: str
    strategyParams: StrategyParams
    chunks: list[DocumentChunk] = Field(..., min_length=1)
    totalCodePoints: int = Field(..., ge=0)
    createdAt: AwareDatetime


class Assignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fragmentId: str
    assignment: Literal['processed', 'context', 'blocked']
    chunkId: RequestId | None
    reason: str | None = None


class ChunkCoverageReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    chunkManifestChecksum: str
    totalFragments: int = Field(..., ge=0)
    processedFragments: int = Field(..., ge=0)
    contextFragments: int = Field(..., ge=0)
    blockedFragments: int = Field(..., ge=0)
    assignments: list[Assignment]


class Input(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bundle: ParsedDocumentBundle
    documentChecksum: str = Field(..., min_length=8)
    strategyParams: StrategyParams


class ChunkingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: Input


class Output(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest: ChunkManifest
    coverage: ChunkCoverageReport


class ItemsModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = Field(None, min_length=1)
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[Items] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[RequestId] | None = Field([], validate_default=True)
    reviewStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    reviewedBy: str | None = None
    reviewedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class ItemsModel1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator10 | Locator11 | Locator12 | Locator13 | Locator14 | Locator15
    quotedText: str | None
    extractionQuality: Literal['GOOD', 'LOW', 'UNPARSED'] | None = 'GOOD'


class TestCaseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    roles: list[Role] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step] = Field(..., min_length=1)
    assertions: list[Assertion] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    approvalStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: RequestId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    approvalHash: str | None = Field(None, min_length=1)
    createdAt: AwareDatetime


class ItemsModel2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    description: str = Field(..., min_length=1)
    kind: Literal[
        'ui.text',
        'ui.element',
        'ui.state',
        'data.value',
        'api.response',
        'download.content',
        'visual',
    ]
    required: bool | None = True
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    operator: Literal[
        'equals',
        'notEquals',
        'contains',
        'notContains',
        'gt',
        'gte',
        'lt',
        'lte',
        'matches',
        'exists',
        'notExists',
    ]
    expected: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class Value5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['dataRef']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Value7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['credential']
    ref: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class SourceClassificationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: SourceClassificationOutput


class Actions3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    effect: Literal['READ', 'WRITE']
    onlyIf: OnlyIf | None = None
    type: Literal['select']
    targetRef: str = Field(
        ...,
        description='bindings 中登记的观察目标引用',
        max_length=128,
        min_length=1,
        pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$',
    )
    value: Value4 | Value5 | Value6 | Value7


class PlanProposalOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[
        Actions | Actions1 | Actions2 | Actions3 | Actions4 | Actions5 | Actions6
    ] = Field(..., max_length=100)
    targets: list[Target]
    blockedReasons: list[str] | None = []


class PlanProposalResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: PlanProposalOutput


class CaseDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[RequestId] = Field(..., min_length=1)
    roles: list[Role] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step1] = Field(..., min_length=1)
    assertions: list[ItemsModel2] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    dimensions: list[
        Literal[
            'HAPPY_PATH',
            'INVALID_INPUT',
            'BOUNDARY',
            'PERMISSION',
            'STATE',
            'CROSS_MODULE',
            'PERSISTENCE',
        ]
    ] = Field(..., min_length=1)


class CaseGenerationOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseDrafts: list[CaseDraft]
    coverageMap: list[CoverageMapItem]
    blockedRequirements: list[BlockedRequirement]


class DocumentParseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: ParsedDocumentBundle


class RuleExtractionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: RuleExtractionOutput


class CaseGenerationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: CaseGenerationOutput


class SourceChange1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['added']
    old: None
    new: ItemsModel1
    reason: None


class SourceChange2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['removed']
    old: ItemsModel1
    new: None
    reason: None


class SourceChange3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['modified']
    old: ItemsModel1
    new: ItemsModel1
    reason: None


class SourceChange4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    kind: Literal['uncertain']
    old: ItemsModel1
    new: ItemsModel1 | None
    reason: str = Field(..., min_length=1)


class SourceChangeReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str = Field(..., min_length=1)
    oldDocumentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    newDocumentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    changes: list[SourceChange1 | SourceChange2 | SourceChange3 | SourceChange4] = (
        Field(..., max_length=40000)
    )


class ImpactAnalysisInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceReports: list[SourceChangeReport] = Field(..., max_length=100)
    approvedRuleVersions: list[ItemsModel]
    approvedCaseVersions: list[TestCaseModel]


class ChangeReviewAnalysisInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comparison: SourceComparisonInput
    approvedRuleVersions: list[ItemsModel] = Field(..., max_length=500)
    approvedCaseVersions: list[TestCaseModel] = Field(..., max_length=500)


class ChangeReviewAnalysisOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceReport: SourceChangeReport
    impact: ImpactAnalysisOutput


class ChangeReviewAnalysisRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: ChangeReviewAnalysisInput


class ChangeReviewAnalysisResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: ChangeReviewAnalysisOutput


class ChunkingResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: Output


class IntelligenceContracts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    SourceClassificationInput_1: SourceClassificationInput = Field(
        ..., alias='SourceClassificationInput'
    )
    SourceClassificationOutput_1: SourceClassificationOutput = Field(
        ..., alias='SourceClassificationOutput'
    )
    SourceClassificationRequest_1: SourceClassificationRequest = Field(
        ..., alias='SourceClassificationRequest'
    )
    SourceClassificationResponse_1: SourceClassificationResponse = Field(
        ..., alias='SourceClassificationResponse'
    )
    PlanProposalInput_1: PlanProposalInput = Field(..., alias='PlanProposalInput')
    PlanProposalOutput_1: PlanProposalOutput = Field(..., alias='PlanProposalOutput')
    PlanProposalRequest_1: PlanProposalRequest = Field(..., alias='PlanProposalRequest')
    PlanProposalResponse_1: PlanProposalResponse = Field(
        ..., alias='PlanProposalResponse'
    )
    ParsedDocumentBundle_1: ParsedDocumentBundle = Field(
        ..., alias='ParsedDocumentBundle'
    )
    RuleExtractionInput_1: RuleExtractionInput = Field(..., alias='RuleExtractionInput')
    RuleExtractionOutput_1: RuleExtractionOutput = Field(
        ..., alias='RuleExtractionOutput'
    )
    CaseGenerationInput_1: CaseGenerationInput = Field(..., alias='CaseGenerationInput')
    CaseGenerationOutput_1: CaseGenerationOutput = Field(
        ..., alias='CaseGenerationOutput'
    )
    ModelResponse_1: ModelResponse = Field(..., alias='ModelResponse')
    TextModelRequest_1: TextModelRequest = Field(..., alias='TextModelRequest')
    VisionModelRequest_1: VisionModelRequest = Field(..., alias='VisionModelRequest')
    DocumentParseInput_1: DocumentParseInput = Field(..., alias='DocumentParseInput')
    DocumentParseRequest_1: DocumentParseRequest = Field(
        ..., alias='DocumentParseRequest'
    )
    DocumentParseResponse_1: DocumentParseResponse = Field(
        ..., alias='DocumentParseResponse'
    )
    RuleExtractionRequest_1: RuleExtractionRequest = Field(
        ..., alias='RuleExtractionRequest'
    )
    RuleExtractionResponse_1: RuleExtractionResponse = Field(
        ..., alias='RuleExtractionResponse'
    )
    CaseGenerationRequest_1: CaseGenerationRequest = Field(
        ..., alias='CaseGenerationRequest'
    )
    CaseGenerationResponse_1: CaseGenerationResponse = Field(
        ..., alias='CaseGenerationResponse'
    )
    InvocationRecord_1: InvocationRecord = Field(..., alias='InvocationRecord')
    SourceChange: SourceChange1 | SourceChange2 | SourceChange3 | SourceChange4
    SourceComparisonInput_1: SourceComparisonInput = Field(
        ..., alias='SourceComparisonInput'
    )
    SourceChangeReport_1: SourceChangeReport = Field(..., alias='SourceChangeReport')
    ImpactAnalysisInput_1: ImpactAnalysisInput = Field(..., alias='ImpactAnalysisInput')
    ImpactAnalysisOutput_1: ImpactAnalysisOutput = Field(
        ..., alias='ImpactAnalysisOutput'
    )
    ChangeReviewAnalysisInput_1: ChangeReviewAnalysisInput = Field(
        ..., alias='ChangeReviewAnalysisInput'
    )
    ChangeReviewAnalysisOutput_1: ChangeReviewAnalysisOutput = Field(
        ..., alias='ChangeReviewAnalysisOutput'
    )
    ChangeReviewAnalysisRequest_1: ChangeReviewAnalysisRequest = Field(
        ..., alias='ChangeReviewAnalysisRequest'
    )
    ChangeReviewAnalysisResponse_1: ChangeReviewAnalysisResponse = Field(
        ..., alias='ChangeReviewAnalysisResponse'
    )
    SpanSlice_1: SpanSlice = Field(..., alias='SpanSlice')
    DocumentChunk_1: DocumentChunk = Field(..., alias='DocumentChunk')
    ChunkManifest_1: ChunkManifest = Field(..., alias='ChunkManifest')
    ChunkCoverageReport_1: ChunkCoverageReport = Field(..., alias='ChunkCoverageReport')
    ChunkingRequest_1: ChunkingRequest = Field(..., alias='ChunkingRequest')
    ChunkingResponse_1: ChunkingResponse = Field(..., alias='ChunkingResponse')


class Model(RootModel[IntelligenceContracts]):
    root: IntelligenceContracts
