# generated by datamodel-codegen:
#   filename:  schema.v1.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Locator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-line']
    startLine: int
    endLine: int


class PathItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class Locator1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['markdown-heading']
    path: list[PathItem] = Field(..., min_length=1)


class Locator2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-paragraph']
    paragraphIndex: int


class Locator3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['docx-cell']
    tableIndex: int
    row: int
    col: int


class Locator4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pdf-page']
    page: int = Field(..., ge=1)


class Locator5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['image-region']
    bbox: list[float] = Field(..., max_length=4, min_length=4)


class CoverageSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalBlocks: int
    goodSpans: int
    lowSpans: int
    unparsedSpans: int


class ProjectGlossaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term: str
    definition: str


class BusinessField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., min_length=1)
    operator: (
        Literal['gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'in', 'between', 'contains']
        | None
    ) = None
    value: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class Clarification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleDraftKeys: list[str] = Field(..., min_length=1)
    question: str = Field(..., min_length=1)
    kind: Literal['MISSING_INFO', 'CONFLICT', 'AMBIGUITY']


class Role(RootModel[str]):
    root: str = Field(..., min_length=1)


class DataSpec1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['create']
    note: str = Field(..., min_length=1)


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str = Field(..., min_length=1)
    action: str = Field(..., min_length=1)
    expectedResult: str | None = None


class Cleanup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['namespace', 'fixture', 'manual']
    note: str | None = None


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputTokens: int
    outputTokens: int
    estimatedCost: float | None = None


class ModelResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parsedJson: Any | None = None
    rawText: str
    repairsApplied: (
        list[Literal['code-fence', 'trailing-comma', 'truncated-json', 'bom']] | None
    ) = []
    provider: Literal['moonshot', 'mock']
    model: str
    requestId: str | None
    usage: Usage
    latencyMs: int
    outcome: Literal['SUCCESS', 'INVALID_OUTPUT', 'TIMEOUT', 'PROVIDER_ERROR']


class TextModelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal['RULE_EXTRACTION', 'CASE_GENERATION', 'VISION_DESCRIBE']
    system: str
    user: str
    outputSchema: Any | None = None
    temperature: float | None = Field(None, ge=0.0, le=1.0)
    maxOutputTokens: int | None = None
    timeoutMs: int = Field(..., ge=1000, le=600000)


class VisionModelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal['VISION_DESCRIBE']
    imageStorageKey: str = Field(..., min_length=1)
    hint: str = Field(..., min_length=1)
    outputSchema: Any | None = None
    timeoutMs: int = Field(..., ge=1000, le=600000)


class DocumentVersionId(RootModel[str]):
    root: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class Items(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., min_length=1)
    operator: (
        Literal['gt', 'gte', 'lt', 'lte', 'eq', 'neq', 'in', 'between', 'contains']
        | None
    ) = None
    value: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    kind: Literal['heading', 'paragraph', 'table', 'listItem', 'image']
    text: str
    page: int | None = None
    imageStorageKey: str | None = None


class Span(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    locator: Locator | Locator1 | Locator2 | Locator3 | Locator4 | Locator5
    quotedText: str | None
    extractionQuality: Literal['GOOD', 'LOW', 'UNPARSED'] | None = 'GOOD'


class ParsedDocumentBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    parseStatus: Literal['PENDING', 'PARSING', 'PARSED', 'FAILED', 'NEEDS_OCR']
    parserVersion: str = Field(..., min_length=1)
    blocks: list[Block]
    spans: list[Span]
    coverageSummary: CoverageSummary
    warnings: list[str] | None = []


class Image(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    storageKey: str
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )


class RuleExtractionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    projectGlossary: list[ProjectGlossaryItem] | None = Field([], validate_default=True)
    documentVersions: list[ParsedDocumentBundle] = Field(..., min_length=1)
    images: list[Image] | None = Field([], validate_default=True)
    promptVersion: str = Field(..., min_length=1)


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    sourceSpanIds: list[DocumentVersionId] = Field(..., min_length=1)


class RuleDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str = Field(..., pattern='^rule-draft-\\d{2,}$')
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = None
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[BusinessField] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[str] | None = []


class UnparsedRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    spanId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: Literal['TABLE_DEGRADED', 'LOW_QUALITY_IMAGE', 'IRRELEVANT', 'OTHER']


class RuleExtractionOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleDrafts: list[RuleDraft]
    clarifications: list[Clarification]
    unparsedRanges: list[UnparsedRange]


class ApprovedRuleVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    version: int = Field(..., ge=1)
    statement: str = Field(..., min_length=1)
    classification: Literal['EXPLICIT', 'INFERRED', 'UNKNOWN']
    role: str | None = Field(None, min_length=1)
    precondition: str | None = None
    action: str = Field(..., min_length=1)
    condition: str | None = None
    expectation: str = Field(..., min_length=1)
    forbiddenBehaviors: list[str] | None = []
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    businessFields: list[Items] | None = Field([], validate_default=True)
    sources: list[Source] | None = Field([], validate_default=True)
    conflictsWith: list[DocumentVersionId] | None = Field([], validate_default=True)
    reviewStatus: (
        Literal['DRAFT', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED'] | None
    ) = 'DRAFT'
    supersedesId: DocumentVersionId | None = None
    origin: Literal['manual', 'model']
    promptVersion: str | None = None
    reviewedBy: str | None = None
    reviewedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class ClarificationSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    ruleVersionIds: list[DocumentVersionId] = Field(..., min_length=1)
    question: str = Field(..., min_length=1)
    answer: str | None = None
    answerSource: str | None = None
    resolvedBy: str | None = None
    resolvedAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class CaseGenerationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvedRuleVersions: list[ApprovedRuleVersion] = Field(..., min_length=1)
    clarificationSources: list[ClarificationSource] | None = Field(
        [], validate_default=True
    )
    roles: list[Role] = Field(..., min_length=1)
    fixtureCapabilities: list[DocumentVersionId] | None = Field(
        [], validate_default=True
    )
    executorCapabilities: list[str] | None = []
    promptVersion: str = Field(..., min_length=1)


class DataSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strategy: Literal['fixture']
    fixtureId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    params: dict[str, str | float | bool] | None = {}


class Assertion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    description: str = Field(..., min_length=1)
    kind: Literal[
        'ui.text',
        'ui.element',
        'ui.state',
        'data.value',
        'api.response',
        'download.content',
        'visual',
    ]
    required: bool | None = True
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    operator: Literal[
        'equals',
        'notEquals',
        'contains',
        'notContains',
        'gt',
        'gte',
        'lt',
        'lte',
        'matches',
        'exists',
        'notExists',
    ]
    expected: str | float | bool | None = None
    unit: str | None = Field(None, min_length=1)


class CaseDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., min_length=1)
    description: str | None = None
    ruleVersionIds: list[DocumentVersionId] = Field(..., min_length=1)
    roles: list[Role] = Field(..., min_length=1)
    preconditions: list[str] | None = []
    dataSpec: DataSpec | DataSpec1
    steps: list[Step] = Field(..., min_length=1)
    assertions: list[Assertion] = Field(..., min_length=1)
    cleanup: Cleanup
    priority: Literal['P0', 'P1', 'P2'] | None = 'P1'
    dimensions: list[
        Literal[
            'HAPPY_PATH',
            'INVALID_INPUT',
            'BOUNDARY',
            'PERMISSION',
            'STATE',
            'CROSS_MODULE',
            'PERSISTENCE',
        ]
    ] = Field(..., min_length=1)


class CoverageMapItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    caseCount: int
    dimensionsCovered: list[str]


class BlockedRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ruleVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    reason: Literal[
        'MISSING_LOGIN',
        'MISSING_FIXTURE',
        'INSUFFICIENT_INFO',
        'OUT_OF_EXECUTOR_CAPABILITY',
    ]
    detail: str = Field(..., min_length=1)


class CaseGenerationOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseDrafts: list[CaseDraft]
    coverageMap: list[CoverageMapItem]
    blockedRequirements: list[BlockedRequirement]


class DocumentParseInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentVersionId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    format: Literal['MARKDOWN', 'TXT', 'DOCX', 'PDF_TEXT', 'PDF_SCANNED', 'PNG', 'JPEG']
    storageKey: str = Field(..., min_length=1)
    checksum: str = Field(..., pattern='^[a-f0-9]{64}$')
    fileSizeBytes: int = Field(..., ge=1, le=20971520)


class DocumentParseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: DocumentParseInput


class RuleExtractionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: RuleExtractionInput


class CaseGenerationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    timeoutMs: int = Field(..., ge=1000, le=600000)
    input: CaseGenerationInput


class InvocationRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Literal['RULE_EXTRACTION', 'CASE_GENERATION', 'VISION_DESCRIBE']
    promptVersion: str = Field(..., min_length=1)
    response: ModelResponse


class DocumentParseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: ParsedDocumentBundle


class RuleExtractionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: RuleExtractionOutput


class CaseGenerationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal['1.0']
    requestId: str = Field(
        ..., max_length=128, min_length=1, pattern='^[a-zA-Z0-9][a-zA-Z0-9._:-]*$'
    )
    mode: Literal['real', 'mock']
    invocations: list[InvocationRecord]
    output: CaseGenerationOutput


class IntelligenceContracts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ParsedDocumentBundle_1: ParsedDocumentBundle = Field(
        ..., alias='ParsedDocumentBundle'
    )
    RuleExtractionInput_1: RuleExtractionInput = Field(..., alias='RuleExtractionInput')
    RuleExtractionOutput_1: RuleExtractionOutput = Field(
        ..., alias='RuleExtractionOutput'
    )
    CaseGenerationInput_1: CaseGenerationInput = Field(..., alias='CaseGenerationInput')
    CaseGenerationOutput_1: CaseGenerationOutput = Field(
        ..., alias='CaseGenerationOutput'
    )
    ModelResponse_1: ModelResponse = Field(..., alias='ModelResponse')
    TextModelRequest_1: TextModelRequest = Field(..., alias='TextModelRequest')
    VisionModelRequest_1: VisionModelRequest = Field(..., alias='VisionModelRequest')
    DocumentParseInput_1: DocumentParseInput = Field(..., alias='DocumentParseInput')
    DocumentParseRequest_1: DocumentParseRequest = Field(
        ..., alias='DocumentParseRequest'
    )
    DocumentParseResponse_1: DocumentParseResponse = Field(
        ..., alias='DocumentParseResponse'
    )
    RuleExtractionRequest_1: RuleExtractionRequest = Field(
        ..., alias='RuleExtractionRequest'
    )
    RuleExtractionResponse_1: RuleExtractionResponse = Field(
        ..., alias='RuleExtractionResponse'
    )
    CaseGenerationRequest_1: CaseGenerationRequest = Field(
        ..., alias='CaseGenerationRequest'
    )
    CaseGenerationResponse_1: CaseGenerationResponse = Field(
        ..., alias='CaseGenerationResponse'
    )
    InvocationRecord_1: InvocationRecord = Field(..., alias='InvocationRecord')


class Model(RootModel[IntelligenceContracts]):
    root: IntelligenceContracts
